import { fluent3d, FLUENT_3D_ITEMS } from "./fluent3dAssets";

const icon = (id: string) => `icon:${id}`;

/** Stickers salon à Noto (couleur cohèrente), Fluent local, sans duotone */
export const DECO_CATS: { key: string; label: string; items: string[] }[] = [
  {
    key: "fluent",
    label: "\u2728 Anim\u00e9s 3D",
    items: FLUENT_3D_ITEMS.map((x) => fluent3d(x.id)),
  },
  {
    key: "nature",
    label: "\u{1F33F} Nature",
    items: [
      icon("noto:cherry-blossom"),
      icon("noto:hibiscus"),
      icon("noto:sunflower"),
      icon("noto:four-leaf-clover"),
      icon("noto:crescent-moon"),
      icon("noto:star"),
      icon("noto:rainbow"),
      icon("noto:snowflake"),
      icon("noto:fire"),
      icon("noto:droplet"),
      icon("noto:leaf-fluttering-in-wind"),
      icon("noto:water-wave"),
    ],
  },
  {
    key: "vibes",
    label: "\u{1F49C} Vibes",
    items: [
      icon("noto:purple-heart"),
      icon("noto:yellow-heart"),
      icon("noto:orange-heart"),
      icon("noto:red-heart"),
      icon("noto:blue-heart"),
      icon("noto:black-heart"),
      icon("noto:white-heart"),
      icon("noto:green-heart"),
      icon("noto:growing-heart"),
      icon("noto:sparkling-heart"),
      icon("noto:glowing-star"),
      icon("noto:high-voltage"),
    ],
  },
  {
    key: "sport",
    label: "\u{1F3C6} Sport & gaming",
    items: [
      icon("noto:trophy"),
      icon("noto:sports-medal"),
      icon("noto:soccer-ball"),
      icon("noto:basketball"),
      icon("noto:tennis"),
      icon("noto:video-game"),
      icon("noto:game-die"),
      icon("noto:joystick"),
      icon("noto:dart"),
      icon("noto:bullseye"),
      icon("noto:bowling"),
      icon("noto:8-ball"),
    ],
  },
  {
    key: "food",
    label: "\u{1F355} Food",
    items: [
      icon("noto:pizza"),
      icon("noto:hamburger"),
      icon("noto:steaming-bowl"),
      icon("noto:sushi"),
      icon("noto:doughnut"),
      icon("noto:cupcake"),
      icon("noto:soft-ice-cream"),
      icon("noto:strawberry"),
      icon("noto:avocado"),
      icon("noto:beverage-box"),
      icon("noto:chocolate-bar"),
      icon("noto:pancakes"),
    ],
  },
  {
    key: "music",
    label: "\u{1F3B5} Musique",
    items: [
      icon("noto:musical-notes"),
      icon("noto:headphone"),
      icon("noto:microphone"),
      icon("noto:guitar"),
      icon("noto:piano"),
      icon("noto:drum"),
      icon("noto:saxophone"),
      icon("noto:trumpet"),
      icon("noto:violin"),
      icon("noto:radio"),
      icon("noto:speaker-high-volume"),
      icon("noto:musical-note"),
    ],
  },
  {
    key: "space",
    label: "\u{1F680} Espace",
    items: [
      icon("noto:rocket"),
      icon("noto:ringed-planet"),
      icon("noto:flying-saucer"),
      icon("noto:star"),
      icon("noto:shooting-star"),
      icon("noto:comet"),
      icon("noto:milky-way"),
      icon("noto:telescope"),
      icon("noto:moon"),
      icon("noto:sun"),
      icon("noto:globe-showing-europe-africa"),
      icon("noto:satellite"),
    ],
  },
  {
    key: "school",
    label: "\u{1F393} STMG",
    items: [
      fluent3d("graduation_cap"),
      fluent3d("books"),
      fluent3d("brain"),
      fluent3d("bullseye"),
      fluent3d("trophy"),
      fluent3d("money_bag"),
      fluent3d("gem_stone"),
      icon("noto:graduation-cap"),
      icon("noto:books"),
      icon("noto:bar-chart"),
      icon("noto:briefcase"),
    ],
  },
  {
    key: "expressions",
    label: "\u{1F3AD} Expressions",
    items: [
      fluent3d("star-struck"),
      fluent3d("smiling_face_with_sunglasses"),
      fluent3d("nerd_face"),
      fluent3d("partying_face"),
      fluent3d("zany_face"),
      fluent3d("melting_face"),
      fluent3d("saluting_face"),
      fluent3d("cat_with_tears_of_joy"),
      icon("noto:heart-eyes"),
      icon("noto:star-struck"),
      icon("noto:smiling-face-with-sunglasses"),
      icon("noto:partying-face"),
      icon("noto:nerd-face"),
      icon("noto:hot-face"),
      icon("noto:exploding-head"),
      icon("noto:smiling-face-with-horns"),
      icon("noto:alien"),
      icon("noto:ghost"),
      icon("noto:robot"),
    ],
  },
];
