# -*- coding: utf-8 -*-
"""Generate src/data/flashcards.json (ASCII-only with \\u escapes) for reliable encoding."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "data" / "flashcards.json"

CARDS = [
    {
        "id": "m1-t1-01",
        "programme": "management_1ere",
        "notion": "Action collective vs individuelle",
        "question": "En quoi l'action collective se distingue-t-elle de l'action individuelle ?",
        "reponse": "L'action individuelle est men�e par une seule personne pour son propre objectif. L'action collective suppose un groupe qui partage un objectif commun et coordonne les t�ches pour l'atteindre.",
        "xp": 10,
    },
    {
        "id": "m1-t1-02",
        "programme": "management_1ere",
        "notion": "Action collective vs rassemblement",
        "question": "Pourquoi le public d'un concert n'est-il pas consid�r� comme une action collective au sens management ?",
        "reponse": "Les spectateurs ne partagent pas un projet commun structur� : motivations personnelles vari�es et absence de coordination des t�ches vers un objectif partag� par le groupe.",
        "xp": 10,
    },
    {
        "id": "m1-t1-03",
        "programme": "management_1ere",
        "notion": "Efficacit� de l'action collective",
        "question": "Pourquoi l'action collective peut-elle �tre plus efficace que l'action individuelle ?",
        "reponse": "Elle mutualise comp�tences, moyens et temps, d�passe les limites individuelles et permet d'envisager des objectifs difficilement atteignables seul.",
        "xp": 8,
    },
    {
        "id": "m1-t1-04",
        "programme": "management_1ere",
        "notion": "Organisation",
        "question": "� partir de quel moment un groupe peut-il cr�er une organisation ?",
        "reponse": "Lorsque le groupe a un objectif commun, s'organise pour l'atteindre et souhaite agir dans la dur�e avec une perspective de p�rennit� : il structure son action et peut se doter d'un statut juridique (personne morale).",
        "xp": 10,
    },
    {
        "id": "m1-t1-05",
        "programme": "management_1ere",
        "notion": "Personne morale",
        "question": "Qu'appelle-t-on une � personne morale � ?",
        "reponse": "Une entit� juridique distincte des personnes physiques qui la composent, dot�e de droits et d'obligations propres (contrats, patrimoine, responsabilit� selon les statuts).",
        "xp": 9,
    },
    {
        "id": "m1-t1-06",
        "programme": "management_1ere",
        "notion": "Objet social",
        "question": "Qu'est-ce que l'objet social d'une organisation ?",
        "reponse": "La d�claration juridique qui fixe sa finalit� et encadre les activit�s autoris�es pour la r�aliser (ex. : commerce de d�tail, prestation de services, action sociale).",
        "xp": 10,
    },
    {
        "id": "m1-t1-07",
        "programme": "management_1ere",
        "notion": "Finalit� lucrative / non lucrative",
        "question": "Quelle diff�rence fondamentale entre une organisation � finalit� lucrative et une organisation � finalit� non lucrative ?",
        "reponse": "La finalit� lucrative vise la r�alisation de b�n�fices pour les associ�s ou actionnaires. La finalit� non lucrative poursuit un int�r�t g�n�ral, social ou culturel sans distribution de profits aux membres.",
        "xp": 10,
    },
    {
        "id": "m1-t1-08",
        "programme": "management_1ere",
        "notion": "Ressources humaines",
        "question": "Qu'entend-on par ressources humaines d'une organisation ?",
        "reponse": "L'ensemble des comp�tences, savoir-faire, savoir-�tre et capacit�s de travail des salari�s, dirigeants et parfois b�n�voles, mobilis�s pour produire des biens ou des services.",
        "xp": 8,
    },
    {
        "id": "m1-t1-09",
        "programme": "management_1ere",
        "notion": "Ressources mat�rielles",
        "question": "Donne deux exemples de ressources mat�rielles mobilis�es par une entreprise.",
        "reponse": "Par exemple : locaux, machines, v�hicules, stocks de marchandises, �quipements informatiques � tout ce qui constitue l'infrastructure physique de production ou de distribution.",
        "xp": 7,
    },
    {
        "id": "m1-t1-10",
        "programme": "management_1ere",
        "notion": "Ressources financi�res",
        "question": "Quelles sont les deux grandes familles de financement des ressources financi�res ?",
        "reponse": "Les capitaux propres (apports des associ�s, r�serves, r�sultat) et la dette (emprunts bancaires, obligations, cr�dits fournisseurs selon les cas).",
        "xp": 9,
    },
    {
        "id": "m1-t1-11",
        "programme": "management_1ere",
        "notion": "Ressources immat�rielles",
        "question": "Cite trois exemples de ressources immat�rielles et explique leur int�r�t.",
        "reponse": "Marque, brevets, savoir-faire organisationnel, logiciels, base de clients : elles peuvent cr�er un avantage concurrentiel durable et ne pas appara�tre comme le mat�riel au bilan.",
        "xp": 10,
    },
    {
        "id": "m1-t1-12",
        "programme": "management_1ere",
        "notion": "Coordination des t�ches",
        "question": "Pourquoi la coordination des t�ches est-elle indispensable dans une action collective organis�e ?",
        "reponse": "Pour �viter les doublons et les oublis, encha�ner les �tapes dans le bon ordre et aligner les efforts individuels sur l'objectif commun.",
        "xp": 8,
    },
    {
        "id": "m1-t2-01",
        "programme": "management_1ere",
        "notion": "Donn�e, information, connaissance",
        "question": "Explique la cha�ne Donn�e ? Information ? Connaissance en une phrase par maillon.",
        "reponse": "La donn�e est un fait brut ; l'information est une donn�e contextualis�e utile au d�cideur ; la connaissance est l'usage op�rationnel de l'information pour agir ou d�cider.",
        "xp": 11,
    },
    {
        "id": "m1-t2-02",
        "programme": "management_1ere",
        "notion": "Syst�me d'information",
        "question": "Qu'est-ce qu'un syst�me d'information (SI) d'entreprise ?",
        "reponse": "L'ensemble organis� des ressources humaines, mat�rielles, logicielles et proc�dures qui collectent, stockent, traitent et diffusent l'information pour le pilotage et les op�rations.",
        "xp": 10,
    },
    {
        "id": "m1-t2-03",
        "programme": "management_1ere",
        "notion": "Veille",
        "question": "Quel est l'objectif principal d'une d�marche de veille pour une organisation ?",
        "reponse": "Anticiper les �volutions de l'environnement (concurrence, r�glementation, technologies, soci�t�) pour s�curiser les d�cisions et rep�rer opportunit�s et risques.",
        "xp": 9,
    },
    {
        "id": "m1-t2-04",
        "programme": "management_1ere",
        "notion": "Indicateurs de performance",
        "question": "� quoi servent des indicateurs de performance (KPI) ?",
        "reponse": "� mesurer l'atteinte des objectifs, suivre l'activit�, comparer dans le temps ou avec des r�f�rences, et nourrir la d�cision avec des donn�es synth�tiques.",
        "xp": 9,
    },
    {
        "id": "m1-t2-05",
        "programme": "management_1ere",
        "notion": "Qualit� de l'information",
        "question": "Cite trois crit�res de qualit� d'une information utile � la d�cision.",
        "reponse": "Par exemple : exactitude, actualit�, pertinence ; on peut ajouter compl�tude et accessibilit� pour les bons utilisateurs.",
        "xp": 9,
    },
    {
        "id": "m1-t3-01",
        "programme": "management_1ere",
        "notion": "Management",
        "question": "En quoi le management consiste-t-il au-del� du simple � donner des ordres � ?",
        "reponse": "Planifier, organiser, coordonner, motiver et contr�ler les activit�s pour atteindre les objectifs, en mobilisant les ressources humaines dans un cadre collectif.",
        "xp": 10,
    },
    {
        "id": "m1-t3-02",
        "programme": "management_1ere",
        "notion": "Leadership vs management",
        "question": "Quelle nuance courante distingue leadership et management ?",
        "reponse": "Le management structure et pilote ; le leadership influence et porte une vision, inspire l'adh�sion. Les deux peuvent coexister chez un m�me dirigeant.",
        "xp": 10,
    },
    {
        "id": "m1-t3-03",
        "programme": "management_1ere",
        "notion": "Innovation incr�mentale / radicale",
        "question": "Diff�rencie innovation incr�mentale et innovation radicale.",
        "reponse": "L'incr�mentale am�liore progressivement un produit ou un process existant. La radicale bouleverse le march� ou la technologie (rupture pour l'utilisateur).",
        "xp": 10,
    },
    {
        "id": "m1-t3-04",
        "programme": "management_1ere",
        "notion": "D�marche qualit�",
        "question": "Quel est l'enjeu principal d'une d�marche qualit� en entreprise ?",
        "reponse": "R�duire les erreurs et les co�ts cach�s, fiabiliser les processus, augmenter la satisfaction client et renforcer la r�putation de l'organisation.",
        "xp": 9,
    },
    {
        "id": "m1-t4-01",
        "programme": "management_1ere",
        "notion": "Diversit� en entreprise",
        "question": "Pourquoi la diversit� des profils peut-elle �tre un atout pour l'entreprise ?",
        "reponse": "Elle enrichit les points de vue, favorise l'innovation par les croisements d'id�es et am�liore la compr�hension de client�les vari�es, � condition d'un management inclusif.",
        "xp": 9,
    },
    {
        "id": "m1-t4-02",
        "programme": "management_1ere",
        "notion": "Intelligence collective",
        "question": "Qu'appelle-t-on intelligence collective dans une organisation ?",
        "reponse": "La capacit� du groupe � produire des solutions ou d�cisions plus pertinentes que chacun isol�ment, gr�ce � la coop�ration et � la mutualisation des savoirs.",
        "xp": 10,
    },
    {
        "id": "m1-t4-03",
        "programme": "management_1ere",
        "notion": "Coop�tition",
        "question": "Qu'est-ce que la coop�tition ?",
        "reponse": "Des entreprises coop�rent sur certains axes (recherche, norme, fili�re) tout en restant concurrentes sur le march� final.",
        "xp": 10,
    },
    {
        "id": "m1-t4-04",
        "programme": "management_1ere",
        "notion": "QVCT",
        "question": "Que d�signe la qualit� de vie et des conditions de travail (QVCT) ?",
        "reponse": "Les dimensions (organisation du travail, charge, autonomie, s�curit�, relations, am�nagements) qui influencent la sant�, le bien-�tre et l'engagement au travail.",
        "xp": 9,
    },
    {
        "id": "m1-mkt-01",
        "programme": "management_1ere",
        "notion": "Marketing � besoin",
        "question": "Qu'est-ce qu'un besoin en marketing ?",
        "reponse": "Une insatisfaction ou une lacune qu'un individu ou une organisation cherche � combler par un produit, un service ou une exp�rience.",
        "xp": 8,
    },
    {
        "id": "m1-mkt-02",
        "programme": "management_1ere",
        "notion": "Marketing � segmentation",
        "question": "Pourquoi segmenter un march� ?",
        "reponse": "Pour regrouper des clients aux attentes proches et adapter l'offre, le prix, la distribution et la communication au lieu de viser tout le monde de la m�me fa�on.",
        "xp": 9,
    },
    {
        "id": "m1-mkt-03",
        "programme": "management_1ere",
        "notion": "Mix marketing (4P)",
        "question": "Quels sont les quatre P classiques du mix marketing ?",
        "reponse": "Produit (ou service), Prix, Place (distribution / lieu de vente), Promotion (communication).",
        "xp": 9,
    },
    {
        "id": "m1-mkt-04",
        "programme": "management_1ere",
        "notion": "�tude de march�",
        "question": "� quoi sert une �tude de march� avant de lancer une offre ?",
        "reponse": "� mesurer la demande, identifier les concurrents, fixer un positionnement prix et rep�rer les freins ou attentes pour r�duire le risque commercial.",
        "xp": 9,
    },
    {
        "id": "m1-rh-01",
        "programme": "management_1ere",
        "notion": "Contrat de travail",
        "question": "Pourquoi formaliser un contrat de travail ?",
        "reponse": "Pour pr�ciser les obligations r�ciproques : identit� des parties, fonction, r�mun�ration, dur�e du travail, cong�s et clauses l�gales obligatoires.",
        "xp": 10,
    },
    {
        "id": "m1-rh-02",
        "programme": "management_1ere",
        "notion": "Recrutement",
        "question": "Pourquoi l'entreprise formalise-t-elle un processus de recrutement ?",
        "reponse": "Pour objectiver les crit�res de comp�tence, respecter la non-discrimination, s�curiser le choix du candidat et anticiper l'int�gration (onboarding).",
        "xp": 9,
    },
    {
        "id": "m1-rh-03",
        "programme": "management_1ere",
        "notion": "GPEC",
        "question": "Quel est l'objectif d'une d�marche GPEC (gestion pr�visionnelle des emplois et comp�tences) ?",
        "reponse": "Anticiper les �volutions d'activit� et de comp�tences pour ajuster formations, recrutements et mobilit�s en coh�rence avec la strat�gie.",
        "xp": 11,
    },
    {
        "id": "mt-st-01",
        "programme": "management_terminale",
        "notion": "Strat�gie d'entreprise",
        "question": "Qu'est-ce qu'une strat�gie d'entreprise ?",
        "reponse": "Les choix de moyens et d'objectifs � long terme pour cr�er de la valeur durablement, en tenant compte des forces internes et des contraintes de l'environnement.",
        "xp": 11,
    },
    {
        "id": "mt-st-02",
        "programme": "management_terminale",
        "notion": "Diagnostic SWOT",
        "question": "Que signifient les quatre lettres du SWOT ?",
        "reponse": "Strengths (forces), Weaknesses (faiblesses), Opportunities (opportunit�s), Threats (menaces) � forces et faiblesses internes, opportunit�s et menaces externes.",
        "xp": 10,
    },
    {
        "id": "mt-st-03",
        "programme": "management_terminale",
        "notion": "Croissance interne / externe",
        "question": "Diff�rencie croissance interne et croissance externe.",
        "reponse": "Interne : d�veloppement par investissements propres, nouveaux sites ou nouveaux produits. Externe : acquisitions, fusions, alliances pour cro�tre en taille ou en comp�tences.",
        "xp": 10,
    },
    {
        "id": "mt-st-04",
        "programme": "management_terminale",
        "notion": "Alliance strat�gique",
        "question": "Qu'est-ce qu'une alliance strat�gique entre entreprises ?",
        "reponse": "Un accord de coop�ration limit� dans le temps ou sur un p�rim�tre (technologie, distribution, R&D) sans fusion compl�te, pour partager risques et ressources.",
        "xp": 10,
    },
    {
        "id": "mt-fi-01",
        "programme": "management_terminale",
        "notion": "Chiffre d'affaires",
        "question": "Comment d�finit-on le chiffre d'affaires ?",
        "reponse": "Le montant des ventes de biens et services factur�s sur une p�riode, hors taxes dans la comptabilit� d'entreprise habituelle en France.",
        "xp": 8,
    },
    {
        "id": "mt-fi-02",
        "programme": "management_terminale",
        "notion": "R�sultat / rentabilit�",
        "question": "Pourquoi un CA �lev� ne suffit-il pas � dire qu'une entreprise est rentable ?",
        "reponse": "Il faut comparer les charges (co�ts, salaires, financements, amortissements) au CA : le r�sultat mesure la rentabilit� apr�s tous les co�ts.",
        "xp": 10,
    },
    {
        "id": "mt-fi-03",
        "programme": "management_terminale",
        "notion": "Tr�sorerie",
        "question": "Quel est le principal risque d'une entreprise � rentable sur le papier � mais en tension de tr�sorerie ?",
        "reponse": "L'impossibilit� de payer � court terme fournisseurs, salaires ou �ch�ances, pouvant conduire � la cessation de paiement malgr� un r�sultat positif diff�r�.",
        "xp": 11,
    },
    {
        "id": "mt-fi-04",
        "programme": "management_terminale",
        "notion": "Fonds de roulement",
        "question": "� quoi sert le fonds de roulement (FR) dans une lecture simplifi�e ?",
        "reponse": "Il mesure les ressources stables disponibles pour financer le cycle d'exploitation ; on le rapproche souvent du BFR pour appr�cier l'�quilibre financier de court terme.",
        "xp": 11,
    },
    {
        "id": "mt-fi-05",
        "programme": "management_terminale",
        "notion": "Marge",
        "question": "Diff�rencie marge brute et marge sur co�ts variables (notions de gestion).",
        "reponse": "La marge brute est g�n�ralement le CA moins le co�t d'achat des marchandises vendues ou de production. La marge sur co�ts variables compare le CA aux seuls co�ts variables pour voir la contribution aux charges fixes.",
        "xp": 11,
    },
    {
        "id": "mt-fi-06",
        "programme": "management_terminale",
        "notion": "Seuil de rentabilit�",
        "question": "Qu'exprime le seuil de rentabilit� ?",
        "reponse": "Le niveau d'activit� (volume ou CA) � partir duquel l'entreprise couvre l'ensemble de ses charges fixes et commence � d�gager un r�sultat positif selon la logique des co�ts retenue.",
        "xp": 11,
    },
    {
        "id": "mt-rse-01",
        "programme": "management_terminale",
        "notion": "RSE",
        "question": "Qu'entend-on par responsabilit� soci�tale des entreprises (RSE) ?",
        "reponse": "L'int�gration volontaire par l'entreprise des pr�occupations sociales, environnementales et de gouvernance dans ses activit�s et sa relation avec les parties prenantes.",
        "xp": 10,
    },
    {
        "id": "mt-rse-02",
        "programme": "management_terminale",
        "notion": "Parties prenantes",
        "question": "Qui sont les parties prenantes (stakeholders) d'une entreprise ?",
        "reponse": "Les acteurs impact�s ou concern�s : salari�s, clients, fournisseurs, actionnaires, collectivit�s, ONG, riverains, etc.",
        "xp": 9,
    },
    {
        "id": "mt-int-01",
        "programme": "management_terminale",
        "notion": "Internationalisation",
        "question": "Cite deux modes d'internationalisation d'une PME et un avantage de chacun.",
        "reponse": "Export : investissement limit�, test des march�s. Implantation ou partenariat local : proximit� client, meilleur contr�le. Les deux r�pondent � des logiques de co�t et de march� diff�rentes.",
        "xp": 11,
    },
    {
        "id": "mt-dig-01",
        "programme": "management_terminale",
        "notion": "Transformation num�rique",
        "question": "La transformation num�rique se limite-t-elle � � digitaliser les papiers � ? Pourquoi ?",
        "reponse": "Non : elle inclut nouveaux mod�les �conomiques, relation client en ligne, pilotage par les donn�es, cybers�curit� et �volution des comp�tences et de l'organisation.",
        "xp": 10,
    },
    {
        "id": "mt-dig-02",
        "programme": "management_terminale",
        "notion": "Mod�le �conomique",
        "question": "Qu'appelle-t-on le mod�le �conomique d'une entreprise ?",
        "reponse": "La logique par laquelle elle cr�e, d�livre et capture de la valeur (proposition de valeur, segments, canaux, structure de co�ts et sources de revenus).",
        "xp": 11,
    },
    {
        "id": "mt-gov-01",
        "programme": "management_terminale",
        "notion": "Gouvernance d'entreprise",
        "question": "Qu'entend-on par gouvernance d'entreprise ?",
        "reponse": "Les r�gles et m�canismes qui r�partissent le pouvoir entre actionnaires, dirigeants et autres parties prenantes pour orienter et contr�ler la strat�gie.",
        "xp": 11,
    },
    {
        "id": "sdgn-org-01",
        "programme": "sdgn",
        "notion": "Action collective organis�e",
        "question": "Quelles conditions pour passer d'une action collective � une organisation juridique ?",
        "reponse": "Objectif commun, coordination des t�ches, mobilisation de ressources, volont� d'agir dans la dur�e, puis mise en conformit� avec un statut juridique (personne morale reconnue par les tiers).",
        "xp": 10,
    },
    {
        "id": "sdgn-org-02",
        "programme": "sdgn",
        "notion": "Types d'organisations",
        "question": "Cite trois formes juridiques courantes d'organisations commerciales.",
        "reponse": "Par exemple : SAS, SARL, SA � formes de soci�t�s reconnues par le droit des soci�t�s (d'autres r�ponses coh�rentes du cours peuvent convenir).",
        "xp": 9,
    },
    {
        "id": "sdgn-org-03",
        "programme": "sdgn",
        "notion": "Association loi 1901",
        "question": "Quelle est la finalit� typique d'une association loi 1901 ?",
        "reponse": "Une finalit� non lucrative : projet collectif (culture, sport, solidarit�) sans partage de b�n�fices entre membres, gestion dans un cadre associatif d�mocratique.",
        "xp": 9,
    },
    {
        "id": "sdgn-si-01",
        "programme": "sdgn",
        "notion": "Composantes du SI",
        "question": "Quelles composantes mat�rielles et immat�rielles constituent le syst�me d'information ?",
        "reponse": "Mat�riel (serveurs, r�seaux, postes), logiciels (ERP, CRM, messagerie), donn�es, proc�dures, et surtout les acteurs humains qui produisent et utilisent l'information.",
        "xp": 10,
    },
    {
        "id": "sdgn-si-02",
        "programme": "sdgn",
        "notion": "ERP",
        "question": "� quoi sert un progiciel de type ERP ?",
        "reponse": "� int�grer les processus m�tier (achats, stocks, production, comptabilit�, RH selon modules) dans une base commune pour fluidifier les flux et harmoniser l'information.",
        "xp": 10,
    },
    {
        "id": "sdgn-si-03",
        "programme": "sdgn",
        "notion": "CRM",
        "question": "Quel est l'objectif principal d'un CRM ?",
        "reponse": "Centraliser l'information sur les clients et prospects pour personnaliser la relation commerciale, suivre les interactions et am�liorer la fid�lisation.",
        "xp": 9,
    },
    {
        "id": "sdgn-si-04",
        "programme": "sdgn",
        "notion": "E-commerce et SI",
        "question": "Pourquoi un site de vente en ligne d�pend-il fortement du SI en coulisses ?",
        "reponse": "Pour la gestion du catalogue, des stocks en temps r�el, du paiement s�curis�, de la logistique et du SAV : toute rupture d'information d�grade le service client.",
        "xp": 10,
    },
    {
        "id": "sdgn-data-01",
        "programme": "sdgn",
        "notion": "Big data",
        "question": "Quels traits caract�risent souvent le � big data � (dimensions en V) ?",
        "reponse": "Volume massif, v�locit� (flux rapides), vari�t� (sources h�t�rog�nes) ; on peut compl�ter par v�racit� et valeur selon les auteurs.",
        "xp": 11,
    },
    {
        "id": "sdgn-data-02",
        "programme": "sdgn",
        "notion": "Open data",
        "question": "Qu'est-ce que l'open data ?",
        "reponse": "La mise � disposition de jeux de donn�es publiques en formats ouverts et r�utilisables pour la transparence et l'innovation citoyenne ou �conomique.",
        "xp": 10,
    },
    {
        "id": "sdgn-data-03",
        "programme": "sdgn",
        "notion": "Data visualisation",
        "question": "Pourquoi visualiser des donn�es (graphiques, tableaux de bord) ?",
        "reponse": "Pour rendre lisibles des volumes complexes, rep�rer tendances et anomalies rapidement et faciliter la communication autour des d�cisions.",
        "xp": 8,
    },
    {
        "id": "sdgn-rgpd-01",
        "programme": "sdgn",
        "notion": "Donn�e personnelle",
        "question": "Qu'est-ce qu'une donn�e personnelle au sens du RGPD ?",
        "reponse": "Toute information se rapportant � une personne physique identifi�e ou identifiable (nom, email, IP, cookie, num�ro client, etc.).",
        "xp": 10,
    },
    {
        "id": "sdgn-rgpd-02",
        "programme": "sdgn",
        "notion": "Finalit� et lic�it�",
        "question": "Pourquoi doit-on d�finir une finalit� avant de collecter des donn�es personnelles ?",
        "reponse": "Le RGPD impose la lic�it� et la limitation des finalit�s : on ne collecte que ce qui est n�cessaire � un objectif d�termin�, explicite et l�gitime, inform� � la personne.",
        "xp": 11,
    },
    {
        "id": "sdgn-rgpd-03",
        "programme": "sdgn",
        "notion": "Minimisation",
        "question": "Qu'est-ce que le principe de minimisation des donn�es ?",
        "reponse": "Ne collecter et ne conserver que des donn�es ad�quates, pertinentes et limit�es � ce qui est n�cessaire aux finalit�s poursuivies.",
        "xp": 10,
    },
    {
        "id": "sdgn-rgpd-04",
        "programme": "sdgn",
        "notion": "Droit d'acc�s",
        "question": "Que permet le droit d'acc�s d'une personne sur ses donn�es ?",
        "reponse": "Obtenir confirmation qu'un traitement existe, acc�s aux donn�es et informations sur les traitements (finalit�s, dur�e, destinataires, etc.).",
        "xp": 10,
    },
    {
        "id": "sdgn-rgpd-05",
        "programme": "sdgn",
        "notion": "DPO",
        "question": "Quel est le r�le du d�l�gu� � la protection des donn�es (DPO) ?",
        "reponse": "Informer et conseiller l'organisation, contr�ler le respect du RGPD, coop�rer avec l'autorit� de contr�le et �tre un point de contact pour les personnes concern�es.",
        "xp": 11,
    },
    {
        "id": "sdgn-rgpd-06",
        "programme": "sdgn",
        "notion": "Violation de donn�es",
        "question": "Que doit faire l'entreprise en cas de violation de donn�es personnelles (fuite) ?",
        "reponse": "Analyser le risque pour les personnes, documenter l'incident, notifier l'autorit� sous 72 h si obligation, et parfois informer les personnes concern�es sans retard injustifi�.",
        "xp": 11,
    },
    {
        "id": "sdgn-rgpd-07",
        "programme": "sdgn",
        "notion": "Consentement",
        "question": "Quand le consentement est-il une base l�gale valable pour traiter des donn�es ?",
        "reponse": "Lorsqu'il est libre, sp�cifique, �clair� et univoque : la personne comprend pour quoi elle accepte et peut retirer son consentement sans difficult� excessive.",
        "xp": 10,
    },
    {
        "id": "sdgn-rgpd-08",
        "programme": "sdgn",
        "notion": "Sous-traitance",
        "question": "Qu'impose le RGPD lorsqu'un responsable de traitement fait appel � un sous-traitant ?",
        "reponse": "Un contrat �crit encadrant instructions, s�curit� et confidentialit� ; le responsable de traitement reste redevable envers les personnes concern�es.",
        "xp": 11,
    },
    {
        "id": "sdgn-cyb-01",
        "programme": "sdgn",
        "notion": "Cybers�curit�",
        "question": "Cite la � triade CIA � utilis�e en s�curit� de l'information.",
        "reponse": "Confidentialit�, int�grit�, disponibilit�.",
        "xp": 11,
    },
    {
        "id": "sdgn-cyb-02",
        "programme": "sdgn",
        "notion": "Phishing",
        "question": "Qu'est-ce que l'hame�onnage (phishing) ?",
        "reponse": "Une tentative d'escroquerie par message (mail, SMS) imitant une entit� de confiance pour voler identifiants ou donn�es ou d�clencher un paiement frauduleux.",
        "xp": 9,
    },
    {
        "id": "sdgn-iot-01",
        "programme": "sdgn",
        "notion": "Objets connect�s",
        "question": "Quel enjeu de gestion lie-t-on aux objets connect�s en entreprise ?",
        "reponse": "Des flux de donn�es en temps r�el pour le pilotage, mais aussi une surface d'attaque accrue, la s�curit� et le respect du RGPD selon les cas.",
        "xp": 10,
    },
    {
        "id": "sdgn-bchain-01",
        "programme": "sdgn",
        "notion": "Blockchain (notions)",
        "question": "Quelle propri�t� d'une cha�ne de blocs est utile pour la tra�abilit� ?",
        "reponse": "Un registre distribu� difficilement alt�rable : les blocs encha�n�s permettent de tracer des op�rations avec consensus (selon le type de cha�ne).",
        "xp": 11,
    },
    {
        "id": "sdgn-dec-01",
        "programme": "sdgn",
        "notion": "D�cision semi-structur�e",
        "question": "Qu'est-ce qu'une d�cision semi-structur�e ?",
        "reponse": "Une d�cision o� une partie du probl�me peut �tre mod�lis�e ou aid�e par des donn�es, mais o� le jugement humain reste n�cessaire pour l'arbitrage final.",
        "xp": 10,
    },
    {
        "id": "sdgn-dec-02",
        "programme": "sdgn",
        "notion": "Tableau de bord",
        "question": "Diff�rencie reporting historique et tableau de bord d�cisionnel.",
        "reponse": "Le reporting restitue surtout le pass�. Le tableau de bord s�lectionne des indicateurs cl�s pour le pilotage en cours et l'aide � la d�cision.",
        "xp": 9,
    },
    {
        "id": "sdgn-eth-01",
        "programme": "sdgn",
        "notion": "�thique des algorithmes",
        "question": "Pourquoi un syst�me d'aide � la d�cision algorithmique peut-il poser un probl�me d'�quit� ?",
        "reponse": "Si les donn�es d'apprentissage reproduisent des biais historiques, le mod�le peut discriminer ; d'o� audits, transparence et gouvernance des donn�es.",
        "xp": 11,
    },
    {
        "id": "sdgn-cloud-01",
        "programme": "sdgn",
        "notion": "Cloud computing",
        "question": "Quels sont deux avantages et un risque du cloud pour une organisation ?",
        "reponse": "Avantages : �lasticit� des capacit�s, r�duction d'investissements mat�riels, acc�s distant. Risques : d�pendance au fournisseur, localisation des donn�es, exigences de conformit� (RGPD).",
        "xp": 10,
    },
    {
        "id": "sdgn-proc-01",
        "programme": "sdgn",
        "notion": "Urbanisation du SI",
        "question": "En une phrase : qu'est-ce qu'urbaniser le SI ?",
        "reponse": "Organiser applications et donn�es par domaines et interfaces pour r�duire la complexit�, les doublons et faciliter des �volutions coordonn�es.",
        "xp": 11,
    },
    {
        "id": "sdgn-proc-02",
        "programme": "sdgn",
        "notion": "Tra�abilit�",
        "question": "Pourquoi la tra�abilit� des op�rations dans un SI est-elle importante ?",
        "reponse": "Pour contr�ler les processus, prouver la conformit�, d�tecter erreurs ou fraudes et r�pondre aux obligations l�gales ou clients.",
        "xp": 9,
    },
    {
        "id": "sdgn-arch-01",
        "programme": "sdgn",
        "notion": "Sch�ma directeur SI",
        "question": "� quoi sert un sch�ma directeur (plan strat�gique du SI) ?",
        "reponse": "� aligner les investissements informatiques sur la strat�gie m�tier sur plusieurs ann�es : priorit�s, budgets, migrations et gestion des risques.",
        "xp": 10,
    },
    {
        "id": "sdgn-int-01",
        "programme": "sdgn",
        "notion": "API",
        "question": "Pourquoi les API sont-elles centrales dans les architectures modernes ?",
        "reponse": "Elles �changent donn�es et services entre applications de fa�on standardis�e, ouvrent l'�cosyst�me (partenaires, mobile) et font �voluer le SI par briques.",
        "xp": 10,
    },
    {
        "id": "sdgn-mob-01",
        "programme": "sdgn",
        "notion": "BYOD",
        "question": "Quel risque associe-t-on au BYOD (appareil personnel au travail) ?",
        "reponse": "M�lange vie pro/perso, fuite de donn�es ; il faut s�curiser l'acc�s (MFA, conteneurisation) et clarifier la propri�t� des donn�es sur l'appareil.",
        "xp": 10,
    },
]

PAYLOAD = {
    "version": 1,
    "cards": CARDS,
}

OUT.write_text(json.dumps(PAYLOAD, ensure_ascii=True, indent=2), encoding="ascii")
print("Wrote", OUT, "cards:", len(CARDS))
