/** Banque Duel : SDGN chapitre 7 - grande banque pour limiter les répétitions (générée par scripts/generate-duel-qcm-bank.mjs). */

export type DuelMatiere = "Management" | "Sciences de Gestion" | "Droit" | "Économie";
export type DuelDifficulte = "facile" | "moyen";

export type DuelQcmSource = {
  id: string;
  matiere: DuelMatiere;
  difficulte: DuelDifficulte;
  question: string;
  choix: [string, string, string, string];
  bonIndex: 0 | 1 | 2 | 3;
};

export const DUEL_QCM_BANK: DuelQcmSource[] = [
  {
    id: "sdgn7-01",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "La visioconférence sert surtout à :",
    choix: ["Remplacer tout travail sur site", "Réunir à distance des collaborateurs et échanger en direct", "Supprimer les e-mails internes", "Héberger les bases de données de l'entreprise"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-02",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un outil de messagerie instantanée relève surtout de la famille :",
    choix: ["Stockage", "Organisation", "Communication", "Création"],
    bonIndex: 2,
  },
  {
    id: "sdgn7-03",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un drive partagé en équipe illustre surtout la famille d'outils :",
    choix: ["Communication", "Organisation", "Stockage", "Création"],
    bonIndex: 2,
  },
  {
    id: "sdgn7-04",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Le travail collaboratif avec le numérique vise notamment à :",
    choix: ["Éliminer toute réunion", "Mutualiser les savoir-faire et coopérer, y compris à distance", "Interdire le télétravail", "Remplacer le management par des algorithmes"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-05",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'e-communication désigne surtout :",
    choix: ["Uniquement la publicité télé", "La communication de l'organisation sur Internet et les médias sociaux", "Les contrats papier signés en mairie", "La comptabilité analytique"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-06",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Par rapport aux réseaux sociaux personnels, les réseaux sociaux professionnels :",
    choix: ["Sont toujours publics sans modération", "Ciblent la vie privée uniquement", "Mettent l'accent sur le réseau, l'emploi et les compétences liées au travail", "Interdisent tout partage de fichiers"],
    bonIndex: 2,
  },
  {
    id: "sdgn7-07",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Une communauté en ligne peut être utile à l'organisation parce qu'elle :",
    choix: ["Remplace le siège social", "Rassemble des acteurs autour d'un thème et produit des échanges d'information", "Supprime la hiérarchie", "Garantit l'anonymat total des clients"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-08",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Dans le réseau informatique de l'organisation, le serveur joue notamment le rôle de :",
    choix: ["Remplacer les collaborateurs", "Support pour échanger des données, stocker l'information et communiquer", "Bloquer Internet", "Imprimer les factures clients uniquement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-09",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Mettre en place un réseau informatique comporte des risques tels que :",
    choix: ["Uniquement des gains de productivité", "Perte de données ou interruption des services, entre autres", "La disparition du besoin de sauvegarde", "L'interdiction légale du télétravail"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-10",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Les droits d'accès au réseau sont en général restreints pour :",
    choix: ["Augmenter le nombre de mots de passe oublies", "Limiter ce que chacun peut voir ou modifier et renforcer la sécurité", "Supprimer l'intranet", "Interdire la visioconférence"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-11",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'administrateur réseau s'occupe typiquement de :",
    choix: ["Vendre les produits en magasin", "La gestion et la sécurisation de l'infrastructure réseau", "Rédiger les contrats commerciaux", "Définir seul la stratégie marketing"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-12",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'intranet, par rapport à Internet :",
    choix: ["Est ouvert a tout le monde sans filtre", "Est un réseau interne reserve aux membres de l'organisation", "Ne transporte aucune donnee", "Remplace toujours l'extranet"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-13",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'extranet prolonge souvent l'intranet pour :",
    choix: ["Publier des contenus grand public sans contrôle", "Donner un accès contrôlé à des partenaires extérieurs autorisés", "Supprimer les serveurs", "Remplacer la comptabilité"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-14",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un réseau social d'entreprise (RSE) est en général :",
    choix: ["Ouvert comme un réseau grand public sans identification", "Un espace interne destine aux collaborateurs de l'organisation", "Reserve exclusivement aux clients finaux", "Un logiciel de paie"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-15",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un intérêt du RSE pour la performance peut être :",
    choix: ["Supprimer toute communication hiérarchique", "Fluidifier les échanges entre métiers et accélérer les réponses", "Interdire le travail en équipe", "Éliminer les projets transverses"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-16",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'intelligence collective repose surtout sur :",
    choix: ["Un seul expert qui decide pour tous", "Les interactions entre personnes qui mettent en commun leurs idées", "La suppression des réunions", "Uniquement des robots"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-17",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Dans l'exemple des filtres anti-spam du cours, l'IA sert surtout à :",
    choix: ["Remplacer les salariés", "Traiter des données pour classer ou filtrer automatiquement certains messages", "Supprimer Internet", "Gérer les salaires"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-18",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "On parle d'intelligence artificielle parce que :",
    choix: ["Les ordinateurs ont une conscience morale", "Des programmes traitent des données et peuvent s'améliorer sans être une pensée humaine", "Les managers ne décident plus", "Les données ne sont jamais stockées"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-19",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Au sein des organisations, IA et intelligence collective peuvent :",
    choix: ["Toujours se substituer l'une à l'autre sans complémentarité", "Se compléter : l'IA peut libérer du temps pour des tôches à plus forte valeur", "Interdire toute coopération", "Remplacer le réseau informatique"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-20",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un agenda partagé entre équipes relève plutôt de la famille :",
    choix: ["Communication", "Organisation", "Stockage", "Création"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-21",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Le partage d'ecran en visioconférence permet surtout de :",
    choix: ["Couper le micro de tout le monde", "Montrer un document ou une application aux participants", "Supprimer l'historique du chat", "Bloquer la camera obligatoirement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-22",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un wiki d'équipe pour documenter les procédures relève surtout :",
    choix: ["Communication", "Organisation", "Stockage", "Création"],
    bonIndex: 3,
  },
  {
    id: "sdgn7-23",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un tableau Kanban partage (tôches / colonnes) illustre surtout la famille :",
    choix: ["Communication", "Organisation", "Stockage", "Création"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-24",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Une messagerie d'équipe type 'chat' interne relève surtout de :",
    choix: ["Stockage", "Organisation", "Communication", "Création"],
    bonIndex: 2,
  },
  {
    id: "sdgn7-25",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'e-communication inclut notamment :",
    choix: ["Uniquement le courrier postal", "Les actions de communication sur Internet et réseaux sociaux", "La paie des fournisseurs", "La maintenance des ascenseurs"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-26",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Les technologies numériques favorisent la collaboration car elles :",
    choix: ["Suppriment tout besoin humain", "Facilitent échanges et partage de documents à distance", "Interdisent le télétravail", "Remplacent la stratégie"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-27",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un risque des communautés en ligne mal cadrees :",
    choix: ["Trop de clarte", "Diffusion d'informations non fiables ou hors sujet", "Absence totale d'Internet", "Fin automatique du contrat de travail"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-28",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Le travail collaboratif, c'est :",
    choix: ["Travailler seul sans outil", "Travailler avec plusieurs personnes vers un résultat commun", "Refuser les réunions", "Archiver uniquement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-29",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un réseau informatique d'entreprise relie typiquement :",
    choix: ["Uniquement deux smartphones personnels", "Les postes via des équipements et un serveur", "Les clients B2C sans filtre", "Les distributeurs automatiques"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-30",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Le serveur dans le réseau sert aussi de support pour :",
    choix: ["La vente en magasin uniquement", "Stocker et échanger de l'information", "Remplacer le dialogue social", "Supprimer l'intranet"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-31",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "La sécurisation du réseau vise notamment à :",
    choix: ["Publier tous les salaires en ligne", "Réduire les accès non autorisés et protéger les données", "Supprimer les mots de passe", "Ouvrir l'intranet au monde entier"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-32",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Internet est :",
    choix: ["Un réseau interne à une seule entreprise", "Un réseau mondial public reliant de nombreux ordinateurs", "Un logiciel de messagerie", "Un type d'extranet"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-33",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'intranet est accessible en principe à :",
    choix: ["Tout internaute sans compte", "Les membres de l'organisation (collaborateurs)", "Uniquement les concurrents", "Les robots uniquement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-34",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'extranet sert souvent a :",
    choix: ["Remplacer le site vitrine public", "Ouvrir un espace sécurisé vers des partenaires autorisés", "Supprimer les serveurs", "Héberger des jeux vidéo"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-35",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Sur un RSE, les échanges type 'mur' ou fil d'actualite visent :",
    choix: ["La comptabilité générale", "La communication et la coopération entre collaborateurs", "La suppression du management", "Le stockage froid uniquement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-36",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Limiter l'accès à certaines infos selon le métier (RH, finance...) traduit :",
    choix: ["Une absence de réseau", "Une gestion des droits d'accès", "L'interdiction du télétravail", "La fin de l'intelligence collective"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-37",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'intelligence collective peut émerger quand :",
    choix: ["Une seule personne impose sans écoute", "Plusieurs personnes échangent et combinent leurs idées", "L'ordinateur est éteint", "Les clients ne donnent aucun avis"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-38",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'IA au service des équipes peut :",
    choix: ["Remplacer toute décision humaine", "Automatiser des tôches répétitives pour libérer du temps", "Supprimer le besoin d'information", "Éliminer le réseau social d'entreprise"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-39",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Pourquoi l'IA est-elle dite 'artificielle' ?",
    choix: ["Parce qu'elle imite parfaitement la conscience", "Parce que ce sont des programmes qui traitent des données, sans pensée biologique", "Parce qu'elle n'utilise jamais de données", "Parce qu'elle est interdite en Europe"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-40",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un outil de visioconférence appartient a la famille :",
    choix: ["Stockage", "Organisation", "Communication", "Création"],
    bonIndex: 2,
  },
  {
    id: "sdgn7-41",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un espace cloud partage pour fichiers projet relève surtout :",
    choix: ["Communication", "Organisation", "Stockage", "Création"],
    bonIndex: 2,
  },
  {
    id: "sdgn7-42",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Les réseaux sociaux professionnels mettent l'accent sur :",
    choix: ["Les photos de vacances uniquement", "L'emploi, le réseau et les compétences liées au travail", "Les recettes de cuisine", "La vente illégale"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-43",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Les communautés en ligne d'entreprise peuvent aider a :",
    choix: ["Supprimer la veille", "Capitaliser des retours d'expérience et bonnes pratiques", "Eviter toute modération", "Remplacer la loi"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-44",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Le rôle de l'administrateur réseau inclut :",
    choix: ["Vendre en caisse", "Configurer et sécuriser l'infrastructure", "Rédiger les statuts juridiques", "Gérer les stocks physiques uniquement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-45",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un avantage du travail collaboratif numérique :",
    choix: ["Moins de coordination", "Reactivité accrue et mutualisation des savoirs", "Suppression des projets", "Interdiction du partage"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-46",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un risque du réseau informatique cite dans le cours :",
    choix: ["Trop de transparence obligatoire", "Perte de données ou interruption de service", "Absence de serveur", "Interdiction d'e-mail"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-47",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'extranet prolonge l'intranet vers :",
    choix: ["Tout le web sans filtre", "Des acteurs externes autorisés (partenaires)", "Les satellites uniquement", "Les appareils non connectes"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-48",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Decathlon (cas du cours) utilise des outils collaboratifs pour :",
    choix: ["Supprimer les magasins", "Fluidifier le travail entre magasins, logistique et siège", "Interdire la logistique", "Remplacer les collaborateurs par des robots"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-49",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Dans le cas Decathlon, les droits d'accès différenciés servent a :",
    choix: ["Publier tous les salaires", "Limiter l'accès selon les métiers et protéger la confidentialité", "Supprimer l'intranet", "Ouvrir tout à Internet"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-50",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'Oréal (cas du cours) échange avec des partenaires via :",
    choix: ["Une page Facebook sans modération", "Des plateformes numériques sécurisées réservées aux autorisés", "Uniquement le courrier cheval", "Des SMS personnels"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-51",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'Oréal utilise aussi l'IA pour :",
    choix: ["Supprimer les équipes communication", "Automatiser certains tris ou suggestions et libérer du temps", "Interdire les données", "Remplacer les clients"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-52",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Une vidéoconference 'hybride' melange :",
    choix: ["Uniquement des robots", "Participants presents et participants à distance", "Deux intranets incompatibles", "Internet et la television analogique"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-53",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Le moindre privilege (principe de sécurité) consiste a :",
    choix: ["Donner tous les droits a tout le monde", "Donner le minimum de droits necessaires a chaque profil", "Supprimer les administrateurs", "Interdire la sauvegarde"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-54",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un forum interne sur le RSE sert surtout à :",
    choix: ["Payer les fournisseurs", "Discuter et partager autour de sujets de travail", "Héberger des films", "Remplacer le serveur"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-55",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "La difference clef intranet / Internet :",
    choix: ["Aucune", "L'intranet est interne à l'organisation, Internet est public mondial", "Internet est plus petit qu'un intranet", "L'intranet n'utilise pas TCP/IP"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-56",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un calendrier partage pour planifier des lancements produits relève :",
    choix: ["Stockage", "Organisation", "Communication seule", "Création artistique"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-57",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'intelligence collective et l'IA peuvent être :",
    choix: ["Toujours identiques", "Complémentaires : l'humain garde le sens, l'IA aide sur volume ou répétition", "Interdites ensemble", "Réservées aux RH uniquement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-58",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un outil de co-edition de texte (même document en direct) relève surtout :",
    choix: ["Stockage", "Organisation", "Communication", "Création"],
    bonIndex: 3,
  },
  {
    id: "sdgn7-59",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Les communautés en ligne nécessitent souvent :",
    choix: ["Aucune règle", "Un cadre clair (modération, objectifs, charte)", "La suppression du numérique", "L'absence de modération"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-60",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Le réseau social d'entreprise (RSE) vise une communication :",
    choix: ["Uniquement externe grand public", "Interne entre collaborateurs", "Uniquement gouvernementale", "Sans aucun contenu"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-61",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un 'mur' sur un RSE est proche fonctionnellement de :",
    choix: ["Un grand livre comptable", "Un fil d'actualite avec publications et reactions", "Un serveur DNS", "Une machine a cafe"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-62",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "La visioconférence peut réduire :",
    choix: ["Toute interaction humaine", "Les contraintes de deplacement pour certaines réunions", "Le besoin de sécurité", "Les droits d'accès"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-63",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Une panne réseau peut impacter :",
    choix: ["Uniquement les loisirs", "La continuite des services et la collaboration", "La couleur du logo", "Les saisons meteorologiques"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-64",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Les quatre familles d'outils du chapitre incluent :",
    choix: ["Achat, vente, stock, paie", "Communication, organisation, stockage, création", "Marketing, finance, droit, RH", "Internet, intranet, extranet, cloud public"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-65",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'e-communication concerné aussi :",
    choix: ["Uniquement la radio FM", "La presence sur médias sociaux et canaux en ligne", "La menuiserie", "La vente de timbres"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-66",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un partenaire accede a des documents sur un espace dedie :",
    choix: ["C'est typiquement de l'intranet public", "C'est proche de la logique extranet (accès contrôlé)", "C'est toujours illégal", "C'est sans authentification"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-67",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'IA pour suggestions de contenus (cas type) peut aider a :",
    choix: ["Supprimer la création humaine", "Gagner du temps sur le tri ou la preparation", "Éliminer les données clients", "Interdire les campagnes"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-68",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Les droits d'accès restreints cherchent a eviter :",
    choix: ["La collaboration", "Les fuites ou modifications non autorisees", "Les réunions", "Les projets transverses"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-69",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un espace partage 'projet' avec listes de tôches relève surtout :",
    choix: ["Communication", "Organisation", "Stockage pur", "Création vidéo"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-70",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'intranet peut diffuser :",
    choix: ["Les mêmes contenus que n'importe quel site public sans filtre", "Des informations internes (procédure, annuaire, outils)", "Uniquement des publicités externes", "Des virus volontairement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-71",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'extranet peut servir a partager avec des partenaires :",
    choix: ["Toutes les données sans limite", "Documents et indicateurs selon profils autorisés", "Les mots de passe administrateur", "Des contenus personnels des salariés"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-72",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'intelligence collective se nourrit de :",
    choix: ["Le silence total", "Les échanges et la diversité des contributions", "Un seul algorithme", "L'absence d'objectif"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-73",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Filtres anti-spam : l'IA traite surtout :",
    choix: ["Les salaires papier", "Des messages pour les classer / filtrer", "Les contrats de mariage", "La météorologie"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-74",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un outil de sondage rapide après réunion relève plutôt :",
    choix: ["Stockage", "Organisation", "Communication / retour d'information", "Création industrielle"],
    bonIndex: 2,
  },
  {
    id: "sdgn7-75",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "La performance d'une org. numérique dépend aussi de :",
    choix: ["Le numérique seul", "Le cadre, la qualité de l'info et la responsabilite des acteurs", "La suppression des droits", "L'absence de modération"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-76",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Télétravail + outils collaboratifs illustrent :",
    choix: ["La fin du management", "Le travail à distance coordonné par le numérique", "L'interdiction du serveur", "La suppression de l'intranet"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-77",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un risque des RS en entreprise mal pilotes :",
    choix: ["Trop peu de messages", "Atteinte à l'image ou fuite d'information sensible", "Absence d'Internet", "Croissance automatique des ventes"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-78",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "La famille 'création' inclut typiquement :",
    choix: ["Un agenda partagé", "Des outils pour produire contenus ou supports (présentation, design)", "Un serveur DNS", "Un pare-feu"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-79",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "La famille 'organisation' inclut typiquement :",
    choix: ["Uniquement la TV", "Planning, gestion de tôches, coordination de projet", "Un antivirus", "Un routeur seul"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-80",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "La famille 'stockage' sert surtout à :",
    choix: ["Envoyer des SMS", "Conserver et partager des fichiers ou données", "Filtrer le spam", "Gérer la paie"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-81",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un client qui suit une communauté de marque sur RS :",
    choix: ["Est toujours salarié", "Échange avec l'organisation via canaux publics/semi-publics", "Accede à l'intranet", "Devient administrateur réseau"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-82",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Le chapitre distingue souvent RS 'personnels' et RS :",
    choix: ["Satellites", "Professionnels", "Bancaires uniquement", "Medicaux uniquement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-83",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "La sécurité sur réseau d'entreprise inclut souvent :",
    choix: ["Publier tous les mots de passe", "Authentification, mises a jour, sauvegardes", "Supprimer les logs", "Ouvrir tous les ports"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-84",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'administrateur réseau et les droits utilisateurs visent entre autres :",
    choix: ["Augmenter les risques", "Confidentialite et integrite des données", "Supprimer la collaboration", "Interdire l'extranet"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-85",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'IA ne 'comprend' pas comme un humain car :",
    choix: ["Elle est toujours consciente", "Elle applique des règles et modèles statistiques sur des données", "Elle ne traite jamais de données", "Elle est uniquement mécanique a roues"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-86",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un tunnel VPN entre sites peut s'inscrire dans :",
    choix: ["La publicité TV", "La logique de réseau sécurisé entre acteurs de l'org.", "La création musicale", "L'open data obligatoire"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-87",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Decathlon : fluidifier entre magasins et siège grace au numérique va dans le sens :",
    choix: ["De l'intelligence collective et du partage des savoirs", "De la suppression des magasins", "De l'interdiction de la logistique", "Du remplacement des clients"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-88",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'Oréal : communautés en ligne clients servent a :",
    choix: ["Remplacer le produit", "Dialoguer et partager de l'information avec le public", "Supprimer le marketing", "Héberger les salaires"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-89",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un outil de brainstorming en ligne relève surtout :",
    choix: ["Stockage", "Organisation", "Communication", "Création / coopération idées"],
    bonIndex: 3,
  },
  {
    id: "sdgn7-90",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "La modération d'une communauté en ligne sert a :",
    choix: ["Supprimer toute parôle", "Encadrer les échanges et limiter les dérives", "Remplacer le droit", "Éliminer les données"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-91",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'intranet n'est en général pas :",
    choix: ["Reserve aux collaborateurs", "Un réseau interne", "Ouvert a tout le monde comme Internet", "Un outil de communication interne"],
    bonIndex: 2,
  },
  {
    id: "sdgn7-92",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'extranet vs simple site public :",
    choix: ["C'est identique", "L'extranet implique souvent authentification et partenaires", "L'extranet n'existe pas", "Le site public est toujours secret"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-93",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Une réunion avec partage d'ecran facilite :",
    choix: ["La suppression du document", "La comprehension commune d'un même support visuel", "La perte de données", "Le blocage du micro"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-94",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'intelligence collective peut être favorisée par un RSE car :",
    choix: ["Il supprime les échanges", "Il rend visibles questions et réponses entre métiers", "Il interdit les projets", "Il remplace la stratégie"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-95",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un repertoire d'équipe sur l'intranet relève :",
    choix: ["Uniquement de la création", "De la communication et/ou organisation des infos internes", "Du stockage froid sans accès", "De l'extranet public"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-96",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Automatiser le tri d'informations (IA) peut libérer du temps pour :",
    choix: ["Ne plus lire", "Des missions a plus forte valeur ajoutee", "Supprimer la sécurité", "Éliminer les clients"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-97",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Les outils collaboratifs incitent souvent a :",
    choix: ["Revenir uniquement au papier", "Revoir les methodes de travail vers plus de coopération", "Supprimer les managers", "Interdire les documents"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-98",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un risque 'interruption des services' sur réseau signifie :",
    choix: ["Trop de succes commercial", "Pannes ou indisponibilite des outils critiques", "Trop de modération", "Absence de clients"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-99",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'extranet s'adresse plutôt a :",
    choix: ["Tous les internautes anonymes", "Des partenaires externes autorisés", "Les animaux", "Les serveurs uniquement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-100",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "La visioconférence ne remplace pas toujours :",
    choix: ["Le besoin de clarifier par échange synchrone", "La nécessite de cadre humain (écoute, décision)", "Le réseau", "Le cloud"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-101",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un 'drive' avec droits de lecture seule pour certains profils illustre :",
    choix: ["Absence de sécurité", "Des droits d'accès différenciés", "L'open data", "L'Internet public"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-102",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'e-communication peut concerner :",
    choix: ["Uniquement le papier", "Site web, RS, newsletters, contenus en ligne", "La mécanique auto", "La cuisine"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-103",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "La coopération à distance repose sur :",
    choix: ["L'absence d'outils", "Des outils numériques adaptes et des usages clairs", "La suppression du serveur", "L'interdiction de l'intranet"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-104",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un objectif du numérique collaboratif en org. :",
    choix: ["Supprimer la coordination", "Améliorer réactivité et partage des connaissances", "Éliminer les équipes", "Interdire la communication"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-105",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Le filtre anti-spam est un exemple d'usage ou l'IA :",
    choix: ["Remplace les humains pour tout", "Traite automatiquement un grand volume de messages", "Supprime Internet", "Ecrit les lois"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-106",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Choisir un outil d'organisation vs communication :",
    choix: ["C'est la même famille toujours", "Un agenda partagé = organisation ; chat = communication", "Tout est stockage", "Tout est création"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-107",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'intranet peut héberger :",
    choix: ["Des procédures internes et outils métier", "Uniquement des jeux publics", "Des secrets concurrents sans contrôle", "Rien du tout"],
    bonIndex: 0,
  },
  {
    id: "sdgn7-108",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "La complémentarité IA / intelligence collective signifie souvent :",
    choix: ["L'IA supprime le collectif", "Le collectif apporte le sens, l'IA traite le volume ou l'automatisation", "On ne peut choisir qu'un seul outil", "L'IA interdit les communautés"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-109",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un sondage interne sur le RSE sert a :",
    choix: ["Payer les impots", "Recueillir des retours rapides des collaborateurs", "Supprimer l'intranet", "Bloquer Internet"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-110",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "La 'performance' avec outils collaboratifs dépend aussi :",
    choix: ["Uniquement du prix du logiciel", "De la qualité de l'information et du cadre (sécurité, rôles)", "De la suppression des droits", "De l'absence de formation"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-111",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un wiki interne pour procédures = famille :",
    choix: ["Communication", "Organisation", "Stockage", "Création / capitalisation documentaire"],
    bonIndex: 3,
  },
  {
    id: "sdgn7-112",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Decathlon : droits gérés par administrateur réseau pour :",
    choix: ["Publier tout sur Internet", "Confidentialité et sécurité des accès", "Supprimer les magasins", "Remplacer les clients"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-113",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'Oréal : espace partenaires = logique proche de :",
    choix: ["Intranet grand public", "Extranet sécurisé", "Internet sans authentification", "Stockage local sans réseau"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-114",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Les communautés en ligne produisent de l'information utile si :",
    choix: ["Il n'y a aucune règle", "Le cadre et les objectifs sont clairs", "Personne ne participe", "Tout est secret absolu"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-115",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un outil de visio avec lever de main relève :",
    choix: ["Stockage", "Organisation", "Communication / animation de réunion", "Création 3D"],
    bonIndex: 2,
  },
  {
    id: "sdgn7-116",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Réseau informatique : le serveur centralise souvent :",
    choix: ["Les loisirs uniquement", "Fichiers, services et accès pour les postes clients", "La television", "Les panneaux solaires"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-117",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'Internet est accessible :",
    choix: ["Seulement au siège", "A de tres nombreux utilisateurs dans le monde", "Sans connexion", "Uniquement en intranet"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-118",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un RSE amélioré parfois la performance car il :",
    choix: ["Supprime les échanges", "Rend visibles questions et réponses entre personnes qui ne se croisent pas", "Interdit la hiérarchie", "Remplace la stratégie"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-119",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'intelligence collective n'est pas :",
    choix: ["La somme d'échanges et d'idées combinees", "Uniquement un logiciel installe", "Une dynamique humaine", "Une coopération"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-120",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'IA dans suggestions de contenus : risque a mentionner :",
    choix: ["Trop de qualité", "Biais, erreurs ou contenus inadaptes si on ne valide pas", "Absence de données", "Trop de sécurité"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-121",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un tableur partage en temps reel relève surtout :",
    choix: ["Communication", "Organisation", "Stockage", "Création / co-production de données"],
    bonIndex: 3,
  },
  {
    id: "sdgn7-122",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "La difference 'synchrone' (visio) vs 'asynchrone' (forum) :",
    choix: ["Aucune", "Synchrone = même temps reel ; asynchrone = messages decales dans le temps", "Forum = toujours synchrone", "Visio = toujours asynchrone"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-123",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'extranet peut nécessiter :",
    choix: ["Aucune authentification", "Identifiants et contrôle des accès", "Suppression du réseau", "Publicité obligatoire"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-124",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Securiser le réseau : intérêt des profils utilisateurs :",
    choix: ["Donner les mêmes droits a tous", "Adapter les droits au besoin du poste", "Supprimer l'authentification", "Publier les mots de passe"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-125",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un outil de mindmap collaboratif relève :",
    choix: ["Stockage seul", "Organisation / structuration des idées", "Communication uniquement", "Hebergement DNS"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-126",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'e-communication peut toucher :",
    choix: ["Uniquement les salariés", "Clients, prospects, partenaires via canaux en ligne", "Personne", "Uniquement les machines"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-127",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "La visioconférence nécessite généralement :",
    choix: ["Aucune connexion", "Connexion et équipements audio/vidéo adaptes", "Uniquement un fax", "Papier carbone"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-128",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'IA et l'humain : décision stratégique complexe relève souvent :",
    choix: ["Uniquement de l'IA sans relecture", "Du jugement humain avec aide eventuelle des données", "Du hasard", "Des robots uniquement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-129",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un canal 'équipe' dans un outil de messagerie = famille :",
    choix: ["Stockage", "Organisation", "Communication", "Création"],
    bonIndex: 2,
  },
  {
    id: "sdgn7-130",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Pourquoi limiter l'accès aux infos sensibles (RH, finance) ?",
    choix: ["Pour interdire le travail", "Pour réduire les risques de fuite ou d'erreur", "Pour supprimer le numérique", "Pour augmenter les fuites"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-131",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'intranet peut être un point d'entree vers :",
    choix: ["Uniquement Wikipedia publique", "Services internes (notes de frais, annuaire, docs)", "Les comptes clients sans auth", "Rien"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-132",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Decathlon : plusieurs sites + outils collaboratifs = enjeu :",
    choix: ["Supprimer la logistique", "Coordonner et partager l'information entre lieux", "Interdire les magasins", "Remplacer les produits"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-133",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'Oréal : IA + équipes = idée du cours :",
    choix: ["L'IA remplace tout", "L'IA aide sur volume, les équipes sur le sens et la validation", "On supprime les données", "On interdit les campagnes"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-134",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Communauté en ligne : modération sert aussi a :",
    choix: ["Éliminer toute critique", "Garder des échanges constructifs et conformes au cadre", "Publier des secrets", "Supprimer les utilisateurs sans raison"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-135",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un outil de reservation de salles relève :",
    choix: ["Création", "Organisation", "Stockage froid", "Communication externe uniquement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-136",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Réseau d'entreprise : 'client' designe souvent :",
    choix: ["Uniquement un client externe", "Le poste utilisateur qui consomme des services du réseau", "Un avocat", "Un fournisseur de lait"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-137",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'intelligence collective peut être enrichie par :",
    choix: ["Le silence", "La diversité des métiers et retours dans un RSE", "L'absence d'objectif", "Un seul canal"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-138",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Fuite d'information sur RS entreprise : prevention inclut :",
    choix: ["Publier tout", "Formation, charte d'usage et contrôle des accès", "Supprimer les RS", "Interdire les managers"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-139",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un outil de gestion de tickets support relève surtout :",
    choix: ["Création artistique", "Organisation du travail et du suivi", "Stockage de films", "Communication satellite"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-140",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'extranet partenaires vs communauté publique :",
    choix: ["Identique", "Partenaires = accès contrôlé et documents opérationnels", "Communauté = toujours secret defense", "Extranet = sans login"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-141",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "La visioconférence avec transcription automatique relie :",
    choix: ["Papier et crayon", "Communication et aide numérique (IA)", "Bilan comptable", "Serveur physique uniquement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-142",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Chapitre 7 : le numérique dans l'org. impose souvent de penser :",
    choix: ["Uniquement la technique", "Technique + usages + gouvernance (qui voit quoi)", "Uniquement le marketing", "Uniquement la paie"],
    bonIndex: 1,
  },
];

export const DUEL_QUESTIONS_PAR_PARTIE = 8;
/** Temps total chrono (secondes) - assez serre pour limiter la triche. */
export const DUEL_TEMPS_TOTAL_SEC = 72;
