/** Banque Duel : SDGN chapitre 7 - grande banque pour limiter les r├®p├®titions (g├®n├®r├®e par scripts/generate-duel-qcm-bank.mjs). */

export type DuelMatiere = "Management" | "Sciences de Gestion" | "Droit" | "├ëconomie";
export type DuelDifficulte = "facile" | "moyen";

export type DuelQcmSource = {
  id: string;
  matiere: DuelMatiere;
  difficulte: DuelDifficulte;
  question: string;
  choix: [string, string, string, string];
  bonIndex: 0 | 1 | 2 | 3;
};

export const DUEL_QCM_BANK: DuelQcmSource[] = [
  {
    id: "sdgn7-01",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "La visioconf├®rence sert surtout ├á :",
    choix: ["Remplacer tout travail sur site", "R├®unir ├á distance des collaborateurs et ├®changer en direct", "Supprimer les e-mails internes", "H├®berger les bases de donn├®es de l'entreprise"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-02",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un outil de messagerie instantan├®e rel├¿ve surtout de la famille :",
    choix: ["Stockage", "Organisation", "Communication", "Cr├®ation"],
    bonIndex: 2,
  },
  {
    id: "sdgn7-03",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un drive partag├® en ├®quipe illustre surtout la famille d'outils :",
    choix: ["Communication", "Organisation", "Stockage", "Cr├®ation"],
    bonIndex: 2,
  },
  {
    id: "sdgn7-04",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Le travail collaboratif avec le num├®rique vise notamment ├á :",
    choix: ["├ëliminer toute r├®union", "Mutualiser les savoir-faire et coop├®rer, y compris ├á distance", "Interdire le t├®l├®travail", "Remplacer le management par des algorithmes"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-05",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'e-communication d├®signe surtout :",
    choix: ["Uniquement la publicit├® t├®l├®", "La communication de l'organisation sur Internet et les m├®dias sociaux", "Les contrats papier sign├®s en mairie", "La comptabilit├® analytique"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-06",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Par rapport aux r├®seaux sociaux personnels, les r├®seaux sociaux professionnels :",
    choix: ["Sont toujours publics sans mod├®ration", "Ciblent la vie priv├®e uniquement", "Mettent l'accent sur le r├®seau, l'emploi et les comp├®tences li├®es au travail", "Interdisent tout partage de fichiers"],
    bonIndex: 2,
  },
  {
    id: "sdgn7-07",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Une communaut├® en ligne peut ├¬tre utile ├á l'organisation parce qu'elle :",
    choix: ["Remplace le si├¿ge social", "Rassemble des acteurs autour d'un th├¿me et produit des ├®changes d'information", "Supprime la hi├®rarchie", "Garantit l'anonymat total des clients"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-08",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Dans le r├®seau informatique de l'organisation, le serveur joue notamment le r├┤le de :",
    choix: ["Remplacer les collaborateurs", "Support pour ├®changer des donn├®es, stocker l'information et communiquer", "Bloquer Internet", "Imprimer les factures clients uniquement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-09",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Mettre en place un r├®seau informatique comporte des risques tels que :",
    choix: ["Uniquement des gains de productivit├®", "Perte de donn├®es ou interruption des services, entre autres", "La disparition du besoin de sauvegarde", "L'interdiction l├®gale du t├®l├®travail"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-10",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Les droits d'acc├¿s au r├®seau sont en g├®n├®ral restreints pour :",
    choix: ["Augmenter le nombre de mots de passe oublies", "Limiter ce que chacun peut voir ou modifier et renforcer la s├®curit├®", "Supprimer l'intranet", "Interdire la visioconf├®rence"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-11",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'administrateur r├®seau s'occupe typiquement de :",
    choix: ["Vendre les produits en magasin", "La gestion et la s├®curisation de l'infrastructure r├®seau", "R├®diger les contrats commerciaux", "D├®finir seul la strat├®gie marketing"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-12",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'intranet, par rapport ├á Internet :",
    choix: ["Est ouvert a tout le monde sans filtre", "Est un r├®seau interne reserve aux membres de l'organisation", "Ne transporte aucune donnee", "Remplace toujours l'extranet"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-13",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'extranet prolonge souvent l'intranet pour :",
    choix: ["Publier des contenus grand public sans contr├┤le", "Donner un acc├¿s contr├┤l├® ├á des partenaires ext├®rieurs autoris├®s", "Supprimer les serveurs", "Remplacer la comptabilit├®"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-14",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un r├®seau social d'entreprise (RSE) est en g├®n├®ral :",
    choix: ["Ouvert comme un r├®seau grand public sans identification", "Un espace interne destine aux collaborateurs de l'organisation", "Reserve exclusivement aux clients finaux", "Un logiciel de paie"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-15",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un int├®r├¬t du RSE pour la performance peut ├¬tre :",
    choix: ["Supprimer toute communication hi├®rarchique", "Fluidifier les ├®changes entre m├®tiers et acc├®l├®rer les r├®ponses", "Interdire le travail en ├®quipe", "├ëliminer les projets transverses"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-16",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'intelligence collective repose surtout sur :",
    choix: ["Un seul expert qui decide pour tous", "Les interactions entre personnes qui mettent en commun leurs id├®es", "La suppression des r├®unions", "Uniquement des robots"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-17",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Dans l'exemple des filtres anti-spam du cours, l'IA sert surtout ├á :",
    choix: ["Remplacer les salari├®s", "Traiter des donn├®es pour classer ou filtrer automatiquement certains messages", "Supprimer Internet", "G├®rer les salaires"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-18",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "On parle d'intelligence artificielle parce que :",
    choix: ["Les ordinateurs ont une conscience morale", "Des programmes traitent des donn├®es et peuvent s'am├®liorer sans ├¬tre une pens├®e humaine", "Les managers ne d├®cident plus", "Les donn├®es ne sont jamais stock├®es"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-19",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Au sein des organisations, IA et intelligence collective peuvent :",
    choix: ["Toujours se substituer l'une ├á l'autre sans compl├®mentarit├®", "Se compl├®ter : l'IA peut lib├®rer du temps pour des t├óches ├á plus forte valeur", "Interdire toute coop├®ration", "Remplacer le r├®seau informatique"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-20",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un agenda partag├® entre ├®quipes rel├¿ve plut├┤t de la famille :",
    choix: ["Communication", "Organisation", "Stockage", "Cr├®ation"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-21",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Le partage d'ecran en visioconf├®rence permet surtout de :",
    choix: ["Couper le micro de tout le monde", "Montrer un document ou une application aux participants", "Supprimer l'historique du chat", "Bloquer la camera obligatoirement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-22",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un wiki d'├®quipe pour documenter les proc├®dures rel├¿ve surtout :",
    choix: ["Communication", "Organisation", "Stockage", "Cr├®ation"],
    bonIndex: 3,
  },
  {
    id: "sdgn7-23",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un tableau Kanban partage (t├óches / colonnes) illustre surtout la famille :",
    choix: ["Communication", "Organisation", "Stockage", "Cr├®ation"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-24",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Une messagerie d'├®quipe type 'chat' interne rel├¿ve surtout de :",
    choix: ["Stockage", "Organisation", "Communication", "Cr├®ation"],
    bonIndex: 2,
  },
  {
    id: "sdgn7-25",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'e-communication inclut notamment :",
    choix: ["Uniquement le courrier postal", "Les actions de communication sur Internet et r├®seaux sociaux", "La paie des fournisseurs", "La maintenance des ascenseurs"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-26",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Les technologies num├®riques favorisent la collaboration car elles :",
    choix: ["Suppriment tout besoin humain", "Facilitent ├®changes et partage de documents ├á distance", "Interdisent le t├®l├®travail", "Remplacent la strat├®gie"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-27",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un risque des communaut├®s en ligne mal cadrees :",
    choix: ["Trop de clarte", "Diffusion d'informations non fiables ou hors sujet", "Absence totale d'Internet", "Fin automatique du contrat de travail"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-28",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Le travail collaboratif, c'est :",
    choix: ["Travailler seul sans outil", "Travailler avec plusieurs personnes vers un r├®sultat commun", "Refuser les r├®unions", "Archiver uniquement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-29",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un r├®seau informatique d'entreprise relie typiquement :",
    choix: ["Uniquement deux smartphones personnels", "Les postes via des ├®quipements et un serveur", "Les clients B2C sans filtre", "Les distributeurs automatiques"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-30",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Le serveur dans le r├®seau sert aussi de support pour :",
    choix: ["La vente en magasin uniquement", "Stocker et ├®changer de l'information", "Remplacer le dialogue social", "Supprimer l'intranet"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-31",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "La s├®curisation du r├®seau vise notamment ├á :",
    choix: ["Publier tous les salaires en ligne", "R├®duire les acc├¿s non autoris├®s et prot├®ger les donn├®es", "Supprimer les mots de passe", "Ouvrir l'intranet au monde entier"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-32",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Internet est :",
    choix: ["Un r├®seau interne ├á une seule entreprise", "Un r├®seau mondial public reliant de nombreux ordinateurs", "Un logiciel de messagerie", "Un type d'extranet"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-33",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'intranet est accessible en principe ├á :",
    choix: ["Tout internaute sans compte", "Les membres de l'organisation (collaborateurs)", "Uniquement les concurrents", "Les robots uniquement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-34",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'extranet sert souvent a :",
    choix: ["Remplacer le site vitrine public", "Ouvrir un espace s├®curis├® vers des partenaires autoris├®s", "Supprimer les serveurs", "H├®berger des jeux vid├®o"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-35",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Sur un RSE, les ├®changes type 'mur' ou fil d'actualite visent :",
    choix: ["La comptabilit├® g├®n├®rale", "La communication et la coop├®ration entre collaborateurs", "La suppression du management", "Le stockage froid uniquement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-36",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Limiter l'acc├¿s ├á certaines infos selon le m├®tier (RH, finance...) traduit :",
    choix: ["Une absence de r├®seau", "Une gestion des droits d'acc├¿s", "L'interdiction du t├®l├®travail", "La fin de l'intelligence collective"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-37",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'intelligence collective peut ├®merger quand :",
    choix: ["Une seule personne impose sans ├®coute", "Plusieurs personnes ├®changent et combinent leurs id├®es", "L'ordinateur est ├®teint", "Les clients ne donnent aucun avis"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-38",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'IA au service des ├®quipes peut :",
    choix: ["Remplacer toute d├®cision humaine", "Automatiser des t├óches r├®p├®titives pour lib├®rer du temps", "Supprimer le besoin d'information", "├ëliminer le r├®seau social d'entreprise"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-39",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Pourquoi l'IA est-elle dite 'artificielle' ?",
    choix: ["Parce qu'elle imite parfaitement la conscience", "Parce que ce sont des programmes qui traitent des donn├®es, sans pens├®e biologique", "Parce qu'elle n'utilise jamais de donn├®es", "Parce qu'elle est interdite en Europe"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-40",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un outil de visioconf├®rence appartient a la famille :",
    choix: ["Stockage", "Organisation", "Communication", "Cr├®ation"],
    bonIndex: 2,
  },
  {
    id: "sdgn7-41",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un espace cloud partage pour fichiers projet rel├¿ve surtout :",
    choix: ["Communication", "Organisation", "Stockage", "Cr├®ation"],
    bonIndex: 2,
  },
  {
    id: "sdgn7-42",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Les r├®seaux sociaux professionnels mettent l'accent sur :",
    choix: ["Les photos de vacances uniquement", "L'emploi, le r├®seau et les comp├®tences li├®es au travail", "Les recettes de cuisine", "La vente ill├®gale"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-43",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Les communaut├®s en ligne d'entreprise peuvent aider a :",
    choix: ["Supprimer la veille", "Capitaliser des retours d'exp├®rience et bonnes pratiques", "Eviter toute mod├®ration", "Remplacer la loi"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-44",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Le r├┤le de l'administrateur r├®seau inclut :",
    choix: ["Vendre en caisse", "Configurer et s├®curiser l'infrastructure", "R├®diger les statuts juridiques", "G├®rer les stocks physiques uniquement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-45",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un avantage du travail collaboratif num├®rique :",
    choix: ["Moins de coordination", "Reactivit├® accrue et mutualisation des savoirs", "Suppression des projets", "Interdiction du partage"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-46",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un risque du r├®seau informatique cite dans le cours :",
    choix: ["Trop de transparence obligatoire", "Perte de donn├®es ou interruption de service", "Absence de serveur", "Interdiction d'e-mail"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-47",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'extranet prolonge l'intranet vers :",
    choix: ["Tout le web sans filtre", "Des acteurs externes autoris├®s (partenaires)", "Les satellites uniquement", "Les appareils non connectes"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-48",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Decathlon (cas du cours) utilise des outils collaboratifs pour :",
    choix: ["Supprimer les magasins", "Fluidifier le travail entre magasins, logistique et si├¿ge", "Interdire la logistique", "Remplacer les collaborateurs par des robots"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-49",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Dans le cas Decathlon, les droits d'acc├¿s diff├®renci├®s servent a :",
    choix: ["Publier tous les salaires", "Limiter l'acc├¿s selon les m├®tiers et prot├®ger la confidentialit├®", "Supprimer l'intranet", "Ouvrir tout ├á Internet"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-50",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'Or├®al (cas du cours) ├®change avec des partenaires via :",
    choix: ["Une page Facebook sans mod├®ration", "Des plateformes num├®riques s├®curis├®es r├®serv├®es aux autoris├®s", "Uniquement le courrier cheval", "Des SMS personnels"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-51",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'Or├®al utilise aussi l'IA pour :",
    choix: ["Supprimer les ├®quipes communication", "Automatiser certains tris ou suggestions et lib├®rer du temps", "Interdire les donn├®es", "Remplacer les clients"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-52",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Une vid├®oconference 'hybride' melange :",
    choix: ["Uniquement des robots", "Participants presents et participants ├á distance", "Deux intranets incompatibles", "Internet et la television analogique"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-53",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Le moindre privilege (principe de s├®curit├®) consiste a :",
    choix: ["Donner tous les droits a tout le monde", "Donner le minimum de droits necessaires a chaque profil", "Supprimer les administrateurs", "Interdire la sauvegarde"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-54",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un forum interne sur le RSE sert surtout ├á :",
    choix: ["Payer les fournisseurs", "Discuter et partager autour de sujets de travail", "H├®berger des films", "Remplacer le serveur"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-55",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "La difference clef intranet / Internet :",
    choix: ["Aucune", "L'intranet est interne ├á l'organisation, Internet est public mondial", "Internet est plus petit qu'un intranet", "L'intranet n'utilise pas TCP/IP"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-56",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un calendrier partage pour planifier des lancements produits rel├¿ve :",
    choix: ["Stockage", "Organisation", "Communication seule", "Cr├®ation artistique"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-57",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'intelligence collective et l'IA peuvent ├¬tre :",
    choix: ["Toujours identiques", "Compl├®mentaires : l'humain garde le sens, l'IA aide sur volume ou r├®p├®tition", "Interdites ensemble", "R├®serv├®es aux RH uniquement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-58",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un outil de co-edition de texte (m├¬me document en direct) rel├¿ve surtout :",
    choix: ["Stockage", "Organisation", "Communication", "Cr├®ation"],
    bonIndex: 3,
  },
  {
    id: "sdgn7-59",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Les communaut├®s en ligne n├®cessitent souvent :",
    choix: ["Aucune r├¿gle", "Un cadre clair (mod├®ration, objectifs, charte)", "La suppression du num├®rique", "L'absence de mod├®ration"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-60",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Le r├®seau social d'entreprise (RSE) vise une communication :",
    choix: ["Uniquement externe grand public", "Interne entre collaborateurs", "Uniquement gouvernementale", "Sans aucun contenu"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-61",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un 'mur' sur un RSE est proche fonctionnellement de :",
    choix: ["Un grand livre comptable", "Un fil d'actualite avec publications et reactions", "Un serveur DNS", "Une machine a cafe"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-62",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "La visioconf├®rence peut r├®duire :",
    choix: ["Toute interaction humaine", "Les contraintes de deplacement pour certaines r├®unions", "Le besoin de s├®curit├®", "Les droits d'acc├¿s"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-63",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Une panne r├®seau peut impacter :",
    choix: ["Uniquement les loisirs", "La continuite des services et la collaboration", "La couleur du logo", "Les saisons meteorologiques"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-64",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Les quatre familles d'outils du chapitre incluent :",
    choix: ["Achat, vente, stock, paie", "Communication, organisation, stockage, cr├®ation", "Marketing, finance, droit, RH", "Internet, intranet, extranet, cloud public"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-65",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'e-communication concern├® aussi :",
    choix: ["Uniquement la radio FM", "La presence sur m├®dias sociaux et canaux en ligne", "La menuiserie", "La vente de timbres"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-66",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un partenaire accede a des documents sur un espace dedie :",
    choix: ["C'est typiquement de l'intranet public", "C'est proche de la logique extranet (acc├¿s contr├┤l├®)", "C'est toujours ill├®gal", "C'est sans authentification"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-67",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'IA pour suggestions de contenus (cas type) peut aider a :",
    choix: ["Supprimer la cr├®ation humaine", "Gagner du temps sur le tri ou la preparation", "├ëliminer les donn├®es clients", "Interdire les campagnes"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-68",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Les droits d'acc├¿s restreints cherchent a eviter :",
    choix: ["La collaboration", "Les fuites ou modifications non autorisees", "Les r├®unions", "Les projets transverses"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-69",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un espace partage 'projet' avec listes de t├óches rel├¿ve surtout :",
    choix: ["Communication", "Organisation", "Stockage pur", "Cr├®ation vid├®o"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-70",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'intranet peut diffuser :",
    choix: ["Les m├¬mes contenus que n'importe quel site public sans filtre", "Des informations internes (proc├®dure, annuaire, outils)", "Uniquement des publicit├®s externes", "Des virus volontairement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-71",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'extranet peut servir a partager avec des partenaires :",
    choix: ["Toutes les donn├®es sans limite", "Documents et indicateurs selon profils autoris├®s", "Les mots de passe administrateur", "Des contenus personnels des salari├®s"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-72",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'intelligence collective se nourrit de :",
    choix: ["Le silence total", "Les ├®changes et la diversit├® des contributions", "Un seul algorithme", "L'absence d'objectif"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-73",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Filtres anti-spam : l'IA traite surtout :",
    choix: ["Les salaires papier", "Des messages pour les classer / filtrer", "Les contrats de mariage", "La m├®t├®orologie"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-74",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un outil de sondage rapide apr├¿s r├®union rel├¿ve plut├┤t :",
    choix: ["Stockage", "Organisation", "Communication / retour d'information", "Cr├®ation industrielle"],
    bonIndex: 2,
  },
  {
    id: "sdgn7-75",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "La performance d'une org. num├®rique d├®pend aussi de :",
    choix: ["Le num├®rique seul", "Le cadre, la qualit├® de l'info et la responsabilite des acteurs", "La suppression des droits", "L'absence de mod├®ration"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-76",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "T├®l├®travail + outils collaboratifs illustrent :",
    choix: ["La fin du management", "Le travail ├á distance coordonn├® par le num├®rique", "L'interdiction du serveur", "La suppression de l'intranet"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-77",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un risque des RS en entreprise mal pilotes :",
    choix: ["Trop peu de messages", "Atteinte ├á l'image ou fuite d'information sensible", "Absence d'Internet", "Croissance automatique des ventes"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-78",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "La famille 'cr├®ation' inclut typiquement :",
    choix: ["Un agenda partag├®", "Des outils pour produire contenus ou supports (pr├®sentation, design)", "Un serveur DNS", "Un pare-feu"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-79",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "La famille 'organisation' inclut typiquement :",
    choix: ["Uniquement la TV", "Planning, gestion de t├óches, coordination de projet", "Un antivirus", "Un routeur seul"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-80",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "La famille 'stockage' sert surtout ├á :",
    choix: ["Envoyer des SMS", "Conserver et partager des fichiers ou donn├®es", "Filtrer le spam", "G├®rer la paie"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-81",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un client qui suit une communaut├® de marque sur RS :",
    choix: ["Est toujours salari├®", "├ëchange avec l'organisation via canaux publics/semi-publics", "Accede ├á l'intranet", "Devient administrateur r├®seau"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-82",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Le chapitre distingue souvent RS 'personnels' et RS :",
    choix: ["Satellites", "Professionnels", "Bancaires uniquement", "Medicaux uniquement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-83",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "La s├®curit├® sur r├®seau d'entreprise inclut souvent :",
    choix: ["Publier tous les mots de passe", "Authentification, mises a jour, sauvegardes", "Supprimer les logs", "Ouvrir tous les ports"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-84",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'administrateur r├®seau et les droits utilisateurs visent entre autres :",
    choix: ["Augmenter les risques", "Confidentialite et integrite des donn├®es", "Supprimer la collaboration", "Interdire l'extranet"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-85",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'IA ne 'comprend' pas comme un humain car :",
    choix: ["Elle est toujours consciente", "Elle applique des r├¿gles et mod├¿les statistiques sur des donn├®es", "Elle ne traite jamais de donn├®es", "Elle est uniquement m├®canique a roues"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-86",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un tunnel VPN entre sites peut s'inscrire dans :",
    choix: ["La publicit├® TV", "La logique de r├®seau s├®curis├® entre acteurs de l'org.", "La cr├®ation musicale", "L'open data obligatoire"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-87",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Decathlon : fluidifier entre magasins et si├¿ge grace au num├®rique va dans le sens :",
    choix: ["De l'intelligence collective et du partage des savoirs", "De la suppression des magasins", "De l'interdiction de la logistique", "Du remplacement des clients"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-88",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'Or├®al : communaut├®s en ligne clients servent a :",
    choix: ["Remplacer le produit", "Dialoguer et partager de l'information avec le public", "Supprimer le marketing", "H├®berger les salaires"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-89",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un outil de brainstorming en ligne rel├¿ve surtout :",
    choix: ["Stockage", "Organisation", "Communication", "Cr├®ation / coop├®ration id├®es"],
    bonIndex: 3,
  },
  {
    id: "sdgn7-90",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "La mod├®ration d'une communaut├® en ligne sert a :",
    choix: ["Supprimer toute par├┤le", "Encadrer les ├®changes et limiter les d├®rives", "Remplacer le droit", "├ëliminer les donn├®es"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-91",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'intranet n'est en g├®n├®ral pas :",
    choix: ["Reserve aux collaborateurs", "Un r├®seau interne", "Ouvert a tout le monde comme Internet", "Un outil de communication interne"],
    bonIndex: 2,
  },
  {
    id: "sdgn7-92",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'extranet vs simple site public :",
    choix: ["C'est identique", "L'extranet implique souvent authentification et partenaires", "L'extranet n'existe pas", "Le site public est toujours secret"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-93",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Une r├®union avec partage d'ecran facilite :",
    choix: ["La suppression du document", "La comprehension commune d'un m├¬me support visuel", "La perte de donn├®es", "Le blocage du micro"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-94",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'intelligence collective peut ├¬tre favoris├®e par un RSE car :",
    choix: ["Il supprime les ├®changes", "Il rend visibles questions et r├®ponses entre m├®tiers", "Il interdit les projets", "Il remplace la strat├®gie"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-95",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un repertoire d'├®quipe sur l'intranet rel├¿ve :",
    choix: ["Uniquement de la cr├®ation", "De la communication et/ou organisation des infos internes", "Du stockage froid sans acc├¿s", "De l'extranet public"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-96",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Automatiser le tri d'informations (IA) peut lib├®rer du temps pour :",
    choix: ["Ne plus lire", "Des missions a plus forte valeur ajoutee", "Supprimer la s├®curit├®", "├ëliminer les clients"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-97",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Les outils collaboratifs incitent souvent a :",
    choix: ["Revenir uniquement au papier", "Revoir les methodes de travail vers plus de coop├®ration", "Supprimer les managers", "Interdire les documents"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-98",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un risque 'interruption des services' sur r├®seau signifie :",
    choix: ["Trop de succes commercial", "Pannes ou indisponibilite des outils critiques", "Trop de mod├®ration", "Absence de clients"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-99",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'extranet s'adresse plut├┤t a :",
    choix: ["Tous les internautes anonymes", "Des partenaires externes autoris├®s", "Les animaux", "Les serveurs uniquement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-100",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "La visioconf├®rence ne remplace pas toujours :",
    choix: ["Le besoin de clarifier par ├®change synchrone", "La n├®cessite de cadre humain (├®coute, d├®cision)", "Le r├®seau", "Le cloud"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-101",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un 'drive' avec droits de lecture seule pour certains profils illustre :",
    choix: ["Absence de s├®curit├®", "Des droits d'acc├¿s diff├®renci├®s", "L'open data", "L'Internet public"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-102",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'e-communication peut concern├®r :",
    choix: ["Uniquement le papier", "Site web, RS, newsletters, contenus en ligne", "La m├®canique auto", "La cuisine"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-103",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "La coop├®ration ├á distance repose sur :",
    choix: ["L'absence d'outils", "Des outils num├®riques adaptes et des usages clairs", "La suppression du serveur", "L'interdiction de l'intranet"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-104",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un objectif du num├®rique collaboratif en org. :",
    choix: ["Supprimer la coordination", "Am├®liorer r├®activit├® et partage des connaissances", "├ëliminer les ├®quipes", "Interdire la communication"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-105",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Le filtre anti-spam est un exemple d'usage ou l'IA :",
    choix: ["Remplace les humains pour tout", "Traite automatiquement un grand volume de messages", "Supprime Internet", "Ecrit les lois"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-106",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Choisir un outil d'organisation vs communication :",
    choix: ["C'est la m├¬me famille toujours", "Un agenda partag├® = organisation ; chat = communication", "Tout est stockage", "Tout est cr├®ation"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-107",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'intranet peut h├®berger :",
    choix: ["Des proc├®dures internes et outils m├®tier", "Uniquement des jeux publics", "Des secrets concurrents sans contr├┤le", "Rien du tout"],
    bonIndex: 0,
  },
  {
    id: "sdgn7-108",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "La compl├®mentarit├® IA / intelligence collective signifie souvent :",
    choix: ["L'IA supprime le collectif", "Le collectif apporte le sens, l'IA traite le volume ou l'automatisation", "On ne peut choisir qu'un seul outil", "L'IA interdit les communaut├®s"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-109",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un sondage interne sur le RSE sert a :",
    choix: ["Payer les impots", "Recueillir des retours rapides des collaborateurs", "Supprimer l'intranet", "Bloquer Internet"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-110",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "La 'performance' avec outils collaboratifs d├®pend aussi :",
    choix: ["Uniquement du prix du logiciel", "De la qualit├® de l'information et du cadre (s├®curit├®, r├┤les)", "De la suppression des droits", "De l'absence de formation"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-111",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un wiki interne pour proc├®dures = famille :",
    choix: ["Communication", "Organisation", "Stockage", "Cr├®ation / capitalisation documentaire"],
    bonIndex: 3,
  },
  {
    id: "sdgn7-112",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Decathlon : droits g├®r├®s par administrateur r├®seau pour :",
    choix: ["Publier tout sur Internet", "Confidentialit├® et s├®curit├® des acc├¿s", "Supprimer les magasins", "Remplacer les clients"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-113",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'Or├®al : espace partenaires = logique proche de :",
    choix: ["Intranet grand public", "Extranet s├®curis├®", "Internet sans authentification", "Stockage local sans r├®seau"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-114",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Les communaut├®s en ligne produisent de l'information utile si :",
    choix: ["Il n'y a aucune r├¿gle", "Le cadre et les objectifs sont clairs", "Personne ne participe", "Tout est secret absolu"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-115",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un outil de visio avec lever de main rel├¿ve :",
    choix: ["Stockage", "Organisation", "Communication / animation de r├®union", "Cr├®ation 3D"],
    bonIndex: 2,
  },
  {
    id: "sdgn7-116",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "R├®seau informatique : le serveur centralise souvent :",
    choix: ["Les loisirs uniquement", "Fichiers, services et acc├¿s pour les postes clients", "La television", "Les panneaux solaires"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-117",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'Internet est accessible :",
    choix: ["Seulement au si├¿ge", "A de tres nombreux utilisateurs dans le monde", "Sans connexion", "Uniquement en intranet"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-118",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Un RSE am├®lior├® parfois la performance car il :",
    choix: ["Supprime les ├®changes", "Rend visibles questions et r├®ponses entre personnes qui ne se croisent pas", "Interdit la hi├®rarchie", "Remplace la strat├®gie"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-119",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'intelligence collective n'est pas :",
    choix: ["La somme d'├®changes et d'id├®es combinees", "Uniquement un logiciel installe", "Une dynamique humaine", "Une coop├®ration"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-120",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'IA dans suggestions de contenus : risque a mentionner :",
    choix: ["Trop de qualit├®", "Biais, erreurs ou contenus inadaptes si on ne valide pas", "Absence de donn├®es", "Trop de s├®curit├®"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-121",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un tableur partage en temps reel rel├¿ve surtout :",
    choix: ["Communication", "Organisation", "Stockage", "Cr├®ation / co-production de donn├®es"],
    bonIndex: 3,
  },
  {
    id: "sdgn7-122",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "La difference 'synchrone' (visio) vs 'asynchrone' (forum) :",
    choix: ["Aucune", "Synchrone = m├¬me temps reel ; asynchrone = messages decales dans le temps", "Forum = toujours synchrone", "Visio = toujours asynchrone"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-123",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'extranet peut n├®cessiter :",
    choix: ["Aucune authentification", "Identifiants et contr├┤le des acc├¿s", "Suppression du r├®seau", "Publicit├® obligatoire"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-124",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Securiser le r├®seau : int├®r├¬t des profils utilisateurs :",
    choix: ["Donner les m├¬mes droits a tous", "Adapter les droits au besoin du poste", "Supprimer l'authentification", "Publier les mots de passe"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-125",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un outil de mindmap collaboratif rel├¿ve :",
    choix: ["Stockage seul", "Organisation / structuration des id├®es", "Communication uniquement", "Hebergement DNS"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-126",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'e-communication peut toucher :",
    choix: ["Uniquement les salari├®s", "Clients, prospects, partenaires via canaux en ligne", "Personne", "Uniquement les machines"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-127",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "La visioconf├®rence n├®cessite g├®n├®ralement :",
    choix: ["Aucune connexion", "Connexion et ├®quipements audio/vid├®o adaptes", "Uniquement un fax", "Papier carbone"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-128",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'IA et l'humain : d├®cision strat├®gique complexe rel├¿ve souvent :",
    choix: ["Uniquement de l'IA sans relecture", "Du jugement humain avec aide eventuelle des donn├®es", "Du hasard", "Des robots uniquement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-129",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un canal '├®quipe' dans un outil de messagerie = famille :",
    choix: ["Stockage", "Organisation", "Communication", "Cr├®ation"],
    bonIndex: 2,
  },
  {
    id: "sdgn7-130",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Pourquoi limiter l'acc├¿s aux infos sensibles (RH, finance) ?",
    choix: ["Pour interdire le travail", "Pour r├®duire les risques de fuite ou d'erreur", "Pour supprimer le num├®rique", "Pour augmenter les fuites"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-131",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'intranet peut ├¬tre un point d'entree vers :",
    choix: ["Uniquement Wikipedia publique", "Services internes (notes de frais, annuaire, docs)", "Les comptes clients sans auth", "Rien"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-132",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Decathlon : plusieurs sites + outils collaboratifs = enjeu :",
    choix: ["Supprimer la logistique", "Coordonner et partager l'information entre lieux", "Interdire les magasins", "Remplacer les produits"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-133",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'Or├®al : IA + ├®quipes = id├®e du cours :",
    choix: ["L'IA remplace tout", "L'IA aide sur volume, les ├®quipes sur le sens et la validation", "On supprime les donn├®es", "On interdit les campagnes"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-134",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Communaut├® en ligne : mod├®ration sert aussi a :",
    choix: ["├ëliminer toute critique", "Garder des ├®changes constructifs et conformes au cadre", "Publier des secrets", "Supprimer les utilisateurs sans raison"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-135",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un outil de reservation de salles rel├¿ve :",
    choix: ["Cr├®ation", "Organisation", "Stockage froid", "Communication externe uniquement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-136",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "R├®seau d'entreprise : 'client' designe souvent :",
    choix: ["Uniquement un client externe", "Le poste utilisateur qui consomme des services du r├®seau", "Un avocat", "Un fournisseur de lait"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-137",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "L'intelligence collective peut ├¬tre enrichie par :",
    choix: ["Le silence", "La diversit├® des m├®tiers et retours dans un RSE", "L'absence d'objectif", "Un seul canal"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-138",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Fuite d'information sur RS entreprise : prevention inclut :",
    choix: ["Publier tout", "Formation, charte d'usage et contr├┤le des acc├¿s", "Supprimer les RS", "Interdire les managers"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-139",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "Un outil de gestion de tickets support rel├¿ve surtout :",
    choix: ["Cr├®ation artistique", "Organisation du travail et du suivi", "Stockage de films", "Communication satellite"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-140",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "L'extranet partenaires vs communaut├® publique :",
    choix: ["Identique", "Partenaires = acc├¿s contr├┤l├® et documents op├®rationnels", "Communaut├® = toujours secret defense", "Extranet = sans login"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-141",
    matiere: "Sciences de Gestion",
    difficulte: "facile",
    question: "La visioconf├®rence avec transcription automatique relie :",
    choix: ["Papier et crayon", "Communication et aide num├®rique (IA)", "Bilan comptable", "Serveur physique uniquement"],
    bonIndex: 1,
  },
  {
    id: "sdgn7-142",
    matiere: "Sciences de Gestion",
    difficulte: "moyen",
    question: "Chapitre 7 : le num├®rique dans l'org. impose souvent de penser :",
    choix: ["Uniquement la technique", "Technique + usages + gouvernance (qui voit quoi)", "Uniquement le marketing", "Uniquement la paie"],
    bonIndex: 1,
  },
];

export const DUEL_QUESTIONS_PAR_PARTIE = 8;
/** Temps total chrono (secondes) - assez serre pour limiter la triche. */
export const DUEL_TEMPS_TOTAL_SEC = 72;
