# -*- coding: utf-8 -*-
"""Generate Management Terminale mission packs (chapters 1-15)."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src/data/management/chapters"
OUT.mkdir(parents=True, exist_ok=True)

HDR = 'import type { ManagementMissionExercise } from "../types";\n\n'
DIFFS = ["Facile"] * 3 + ["Moyen"] * 4 + ["Difficile"] * 2 + ["Tres difficile"]
XPS = [120, 130, 140, 180, 190, 210, 230, 260, 280, 360]
MIN_CHARS = [120, 140, 150, 160, 180, 180, 200, 220, 240, 260]


def ts_str(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def exercise(ch, sid, title, diff, xp, mc, *, support, consigne, questions, correction, attendu, etude=False):
    typ = "Etude de cas" if etude else "Exercice"
    ql = ",\n      ".join(ts_str(q) for q in questions)
    return f"""  {{
    id: "mgt{ch}-{sid}",
    title: {ts_str(title)},
    type: "{typ}",
    difficulty: "{diff}",
    xp: {xp},
    minChars: {mc},
    support: {ts_str(support)},
    consigne: {ts_str(consigne)},
    questions: [
      {ql}
    ],
    correctionModele: {ts_str(correction)},
    attendu: {ts_str(attendu)},
  }},"""


def write_chapter(ch, items):
    lines = [f"export const MANAGEMENT_CHAP{ch}_EXERCISES: ManagementMissionExercise[] = ["]
    for i, item in enumerate(items[:10]):
        lines.append(exercise(
            ch, item["sid"], item["title"], DIFFS[i], XPS[i], MIN_CHARS[i],
            support=item["support"], consigne=item["consigne"],
            questions=item["questions"], correction=item["correction"],
            attendu=item["attendu"],
        ))
    for j, item in enumerate(items[10:12]):
        diff = "Difficile" if j == 0 else "Tres difficile"
        xp = 560 if j == 0 else 620
        mc = 400 if j == 0 else 450
        lines.append(exercise(
            ch, item["sid"], item["title"], diff, xp, mc,
            support=item["support"], consigne=item["consigne"],
            questions=item["questions"], correction=item["correction"],
            attendu=item["attendu"], etude=True,
        ))
    lines.append("];")
    (OUT / f"chap{ch}.ts").write_text(HDR + "\n".join(lines) + "\n", encoding="utf-8")
    print(f"chap{ch}.ts")


def item(sid, title, support, consigne, questions, correction, attendu):
    return {
        "sid": sid, "title": title, "support": support, "consigne": consigne,
        "questions": questions, "correction": correction, "attendu": attendu,
    }


def std_questions(notion):
    return [
        f"D\u00e9finis {notion} en t'appuyant sur le cours.",
        f"Applique {notion} au support avec des exemples pr\u00e9cis.",
        f"Quels avantages et limites pour l'organisation ?",
    ]


def std_correction(notion, example):
    return (
        f"1) {notion} : d\u00e9finition conforme au r\u00e9f\u00e9rentiel Management Terminale.\n\n"
        f"2) Application : {example}\n\n"
        f"3) Avantages/limites : \u00e0 argumenter selon le contexte du support."
    )


def std_attendu(notion):
    return f"D\u00e9finition de {notion}, application au support, analyse critique."


def build_chapter(ch, company, sector, city, ca, staff, themes, cas1, cas2):
    exercises = []
    for i, (sid, title, notion, scenario, example) in enumerate(themes):
        exercises.append(item(
            sid, title, scenario,
            f"\u00c0 partir du support, mobilise la notion de {notion} et r\u00e9ponds aux questions.",
            std_questions(notion),
            std_correction(notion, example),
            std_attendu(notion),
        ))
    return exercises + [cas1, cas2]


CHAPTER_DEFS = [
    # ch1
    dict(
        ch=1, company="BioFresh", sector="agroalimentaire bio", city="Lyon", ca="4,2 M\u20ac", staff=85,
        themes=[
            ("e1", "Veille commerciale et signaux faibles", "veille commerciale",
             "BioFresh, PME lyonnaise de paniers bio (CA 4,2 M\u20ac), analyse chaque semaine r\u00e9seaux sociaux, avis clients, prix concurrents et Google Trends. En mars 2025, hausse de 18 % des recherches \u00ab panier sans plastique \u00bb en Auvergne-Rh\u00f4ne-Alpes.",
             "cellule de veille, sources multiples, signal faible sur les emballages"),
            ("e2", "Big Data et personnalisation marketing", "Big Data marketing",
             "MonPanierBio segmente 48 000 clients via CRM : panier moyen 52 \u20ac, fr\u00e9quence, code postal. Campagnes personnalis\u00e9es : taux d'ouverture 34 % vs 12 % g\u00e9n\u00e9rique.",
             "donn\u00e9es massives, segmentation, personnalisation des campagnes"),
            ("e3", "Approches marketing r\u00e9active et anticipative", "approche marketing r\u00e9active",
             "GreenBox baisse ses prix de 8 % d\u00e8s qu'un concurrent promouvoit (r\u00e9active). BioFresh signe des contrats mara\u00eechers six mois avant la saison (anticipative).",
             "GreenBox r\u00e9active vs BioFresh anticipative"),
            ("e4", "Approches proactive et m\u00e9diatrice", "approche marketing m\u00e9diatrice",
             "Locavore met en relation producteurs et clients sans stock (m\u00e9diatrice, commission 12 %). BioFresh lance des jus d\u00e9tox avant demande locale (proactive).",
             "plateforme m\u00e9diatrice vs cr\u00e9ation d'offre proactive"),
            ("e5", "\u00c9tapes de la d\u00e9marche marketing", "d\u00e9marche marketing",
             "Lancement jus d\u00e9tox : \u00e9tude march\u00e9, segmentation urbains 25-40 ans, positionnement sant\u00e9/local, mix 4P, contr\u00f4le taux de r\u00e9achat \u00e0 90 jours.",
             "encha\u00eenement \u00e9tude, segmentation, positionnement, mix, contr\u00f4le"),
            ("e6", "Innovation produit et innovation de proc\u00e9d\u00e9", "innovation de proc\u00e9d\u00e9",
             "BioFresh : jus d\u00e9tox (innovation produit) et ligne conditionnement sous atmosph\u00e8re modifi\u00e9e prolongeant salades de 3 \u00e0 7 jours (-22 % gaspillage).",
             "distinction innovation produit / proc\u00e9d\u00e9, indicateurs de performance"),
            ("e7", "Mod\u00e8les plateforme, freemium et low cost", "mod\u00e8le \u00e9conomique freemium",
             "Locavore : plateforme gratuite + abonnement Pro 29 \u20ac/mois. BioFresh gamme Essentiel -15 % avec packaging simplifi\u00e9 (low cost).",
             "plateforme, freemium, low cost appliqu\u00e9s"),
            ("e8", "Gratuit\u00e9 et capture de valeur", "strat\u00e9gie de gratuit\u00e9",
             "PanierZero : comparateur gratuit financ\u00e9 par pub. BioFresh livraison offerte d\u00e8s 60 \u20ac. Locavore 3 mois Pro gratuits aux producteurs.",
             "gratuit\u00e9 totale, partielle, essai ; mon\u00e9tisation indirecte"),
            ("e9", "Performance sociale et marketing responsable", "performance sociale",
             "BioFresh : 85 % producteurs mieux r\u00e9mun\u00e9r\u00e9s, 40 % femmes cadres, label B Corp 2025, 62 % clients sensibles \u00e0 la performance sociale.",
             "indicateurs sociaux int\u00e9gr\u00e9s au marketing"),
            ("e10", "Synth\u00e8se offre, innovation et mod\u00e8les \u00e9conomiques", "synth\u00e8se marketing",
             "Comit\u00e9 strat\u00e9gique BioFresh : rester producteur-livreur, devenir plateforme ou lancer low cost national. BFR +15 jours, saturation premium \u00e0 Lyon.",
             "comparaison sc\u00e9narios A/B/C, crit\u00e8res marketing et financiers"),
        ],
        cas1=item("cas1", "\u00c9tude de cas : BioFresh face \u00e0 la concurrence plateforme",
                  "BioFresh (4,2 M\u20ac, 85 salari\u00e9s) vs Locavore (+35 %/an) et MonPanierBio (6,8 M\u20ac, Big Data). D\u00e9bat : plateforme propre 500 000 \u20ac, gamme produit ou rachat local.",
                  "R\u00e9dige une analyse type bac : veille, approches marketing, d\u00e9marche, mod\u00e8les \u00e9conomiques, performance sociale.",
                  ["Diagnostic concurrentiel.", "Compare les mod\u00e8les \u00e9conomiques.", "D\u00e9marche marketing 12 mois.", "Valoriser la performance sociale.", "Synth\u00e8se et recommandation."],
                  "Diagnostic veille + concurrence data-driven.\nMod\u00e8les : int\u00e9gr\u00e9 vs plateforme vs e-commerce.\nD\u00e9marche structur\u00e9e et RSE comme diff\u00e9renciation.\nRecommandation hybride \u00e0 argumenter.",
                  "Cas complet chapitre 1."),
        cas2=item("cas2", "\u00c9tude de cas : Lancement BioFresh Go low cost",
                  "BioFresh Go : 25 r\u00e9f\u00e9rences, -20 % vs premium, sous-traitance Espagne, BFR 45\u219262 jours, stock 800 000 \u20ac. M\u00e9fiance \u00ab bio pas cher \u00bb, risque greenwashing.",
                  "Analyse innovation, low cost, marketing, RSE et BFR.",
                  ["Innovation produit/proc\u00e9d\u00e9 ?", "D\u00e9marche marketing rassurante.", "Risques greenwashing.", "Impact BFR et financement.", "Lancer, reporter ou abandonner ?"],
                  "Double innovation produit et proc\u00e9d\u00e9.\nMarketing transparence + certifications.\nGreenwashing \u00e9vit\u00e9 par tra\u00e7abilit\u00e9.\nBFR : cr\u00e9dit CT ou affacturage.\nD\u00e9cision selon tr\u00e9sorerie et image B Corp.",
                  "\u00c9tude de cas structur\u00e9e, d\u00e9cision argument\u00e9e."),
    ),
    # ch2
    dict(
        ch=2, company="Artisana", sector="marketplace artisanat", city="Nantes", ca="3,8 M\u20ac", staff=42,
        themes=[
            ("e1", "Business model et proposition de valeur", "business model",
             "Artisana : marketplace artisanat, commission 15 %, abonnement Vitrine Pro 39 \u20ac/mois, photos pro et r\u00e9f\u00e9rencement.",
             "logique cr\u00e9ation/capture valeur, sources revenus"),
            ("e2", "Cr\u00e9ation de valeur pour le client", "cr\u00e9ation de valeur",
             "Vase 85 \u20ac : artisan 68 \u20ac, Artisana 12,75 \u20ac. Valeur : unicit\u00e9, histoire artisan, soutien local.",
             "valeur artisan vs client, raret\u00e9"),
            ("e3", "Innovation produit : personnalisation", "innovation produit",
             "Offre Sur mesure : gravure et couleurs, panier moyen +28 %, d\u00e9lai 12 jours, investissement SI 95 000 \u20ac.",
             "personnalisation, effets \u00e9conomiques"),
            ("e4", "Mesure performance \u00e9conomique", "performance \u00e9conomique",
             "CA 3,8 M\u20ac (+22 %), marge 38 %, conversion 2,4 %, CAC 18 \u20ac, r\u00e9achat 41 %, seuil rentabilit\u00e9 2,1 M\u20ac.",
             "indicateurs CA, marge, conversion, CAC, r\u00e9achat"),
            ("e5", "Business Model Canvas", "Business Model Canvas",
             "BMC Artisana : segments CSP+, canaux site/Instagram, revenus commissions+abo, ressources cl\u00e9s plateforme et photographes.",
             "9 blocs appliqu\u00e9s \u00e0 Artisana"),
            ("e6", "Performance non financi\u00e8re", "performance sociale",
             "NPS 52, note artisans 4,3/5, litiges 1,2 %, objectif 50 % sous-traitants insertion 2026.",
             "NPS, RSE, indicateurs qualitatifs"),
            ("e7", "\u00c9volution du business model hybride", "\u00e9volution du business model",
             "Showrooms \u00e9ph\u00e9m\u00e8res 5 galeries, 12 % CA sur place, co\u00fbt 45 000 \u20ac/an.",
             "online/offline, risques et opportunit\u00e9s"),
            ("e8", "Cha\u00eene de valeur", "cha\u00eene de valeur",
             "Maillons : s\u00e9lection, photos (+15 % conversion), mise en ligne, SAV 4,6/5.",
             "cr\u00e9ation vs capture de valeur"),
            ("e9", "Tableau de bord de performance", "tableau de bord",
             "CAC pass\u00e9 de 18 \u00e0 26 \u20ac ; d\u00e9cision r\u00e9allocation budget vers parrainage.",
             "pilotage par indicateurs, alerte CAC"),
            ("e10", "Synth\u00e8se business model et croissance", "synth\u00e8se business model",
             "Objectif 8 M\u20ac en 3 ans : international, marque propre ou B2B grande distribution.",
             "trois sc\u00e9narios, indicateurs de suivi"),
        ],
        cas1=item("cas1", "\u00c9tude de cas : Artisana vs Etsy",
                  "Artisana 850 artisans vs Etsy mondial. 15 % artisans multi-plateforme, CA stagne. Plan business model exig\u00e9.",
                  "Analyse strat\u00e9gique compl\u00e8te chapitre 2.",
                  ["Diagnostic vs Etsy.", "Leviers cr\u00e9ation de valeur.", "Plan innovation 18 mois.", "Tableau de bord propos\u00e9.", "Recommandation."],
                  "Diff\u00e9renciation curation/RSE vs volume Etsy.\nInnovation Sur mesure et B2B cadeaux.\nKPI : marge, NPS, CAC, exclusivit\u00e9 artisans.",
                  "Cas complet chapitre 2."),
        cas2=item("cas2", "\u00c9tude de cas : Lancement Artisana Collection",
                  "Marque propre 50 refs, marge 55 %, investissement 420 000 \u20ac, risque conflit artisans.",
                  "Analyse marque propre : BMC, valeur, gouvernance.",
                  ["Impact sur business model ?", "Valeur et risques artisans ?", "Indicateurs succ\u00e8s/\u00e9chec.", "Gouvernance anti-conflit.", "Go/no-go."],
                  "BMC hybride ; plafond 25 % CA marque propre ; artisans associ\u00e9s.\nGo si gouvernance transparente.",
                  "\u00c9tude de cas, d\u00e9cision justifi\u00e9e."),
    ),
    # ch3
    dict(
        ch=3, company="Lumina", sector="\u00e9clairage LED", city="Toulouse", ca="12 M\u20ac", staff=95,
        themes=[
            ("e1", "Financement interne : autofinancement", "autofinancement",
             "Lumina r\u00e9investit 60 % du r\u00e9sultat net (1,8 M\u20ac) pour moderniser l'usine LED. Tr\u00e9sorerie disponible 420 000 \u20ac.",
             "autofinancement, r\u00e9investissement, ind\u00e9pendance financi\u00e8re"),
            ("e2", "Emprunt bancaire et co\u00fbt du capital", "emprunt bancaire",
             "Emprunt 2,5 M\u20ac sur 7 ans, taux 4,2 %, pour ligne automatisation. Annuit\u00e9 420 000 \u20ac.",
             "emprunt, annuit\u00e9, co\u00fbt du financement externe"),
            ("e3", "Augmentation de capital", "augmentation de capital",
             "Ouverture capital \u00e0 un fonds industriel : 3 M\u20ac pour 22 % du capital. Dilution fondateurs 78\u219256 %.",
             "entr\u00e9e investisseur, dilution, gouvernance"),
            ("e4", "Cr\u00e9dit-bail (leasing)", "cr\u00e9dit-bail",
             "Leasing robots soudure : 18 000 \u20ac/mois, option achat 180 000 \u20ac apr\u00e8s 5 ans. Pas d'immobilisation initiale.",
             "cr\u00e9dit-bail vs achat, impact bilan"),
            ("e5", "Subventions et aides publiques", "subventions publiques",
             "Subvention R\u00e9gion Occitanie 350 000 \u20ac pour industrie 4.0, cofinancement 30 % du projet.",
             "subvention, cofinancement, conditions"),
            ("e6", "Besoin en fonds de roulement (BFR)", "besoin en fonds de roulement",
             "BFR Lumina : 2,1 M\u20ac (stocks +45 jours, clients +38 jours, fournisseurs -28 jours). Hausse CA +15 % \u2192 BFR +320 000 \u20ac.",
             "stocks, cr\u00e9ances, dettes fournisseurs, BFR"),
            ("e7", "Choix de financement selon projet", "financement externe",
             "Projet R&D 1,2 M\u20ac : autofinancement partiel 400 000 \u20ac insuffisant. Options : emprunt, lev\u00e9e fonds, subvention.",
             "arbitrage sources de financement"),
            ("e8", "Structure financi\u00e8re et autonomie", "structure financi\u00e8re",
             "Capitaux propres 5,2 M\u20ac, dettes 4,8 M\u20ac, autonomie financi\u00e8re 52 %. Cible 55 %.",
             "capitaux propres, endettement, autonomie"),
            ("e9", "Plan de financement pr\u00e9visionnel", "plan de financement",
             "Investissement 4 M\u20ac : tableau emplois-ressources \u00e9quilibr\u00e9 (apports, emprunt, CB, subvention).",
             "plan de financement, \u00e9quilibre emplois-ressources"),
            ("e10", "Synth\u00e8se financement et BFR", "synth\u00e8se financement",
             "Croissance export +25 % : BFR et investissements simultan\u00e9s. Tr\u00e9sorerie tendue Q3.",
             "combinaison financements, pilotage tr\u00e9sorerie"),
        ],
        cas1=item("cas1", "\u00c9tude de cas : Modernisation usine Lumina",
                  "Investissement 4 M\u20ac automatisati\u00e9on : autofinancement 1,2 M\u20ac, emprunt, CB robots, subvention r\u00e9gion. BFR +400 000 \u20ac.",
                  "Construis un plan de financement complet.",
                  ["Emplois du projet.", "Ressources permanentes et BFR.", "Compare emprunt vs cr\u00e9dit-bail.", "Impact autonomie financi\u00e8re.", "Recommandation."],
                  "Plan \u00e9quilibr\u00e9 4 M\u20ac.\nCB pour robots, emprunt pour b\u00e2timent, subvention R&D.\nSurveiller BFR export.",
                  "Plan de financement structur\u00e9."),
        cas2=item("cas2", "\u00c9tude de cas : Lev\u00e9e de fonds ou endettement",
                  "Fonds propose 5 M\u20ac pour 30 % capital vs banque 5 M\u20ac \u00e0 4,8 %. Fondateurs veulent garder le contr\u00f4le.",
                  "Arbitre lev\u00e9e de fonds vs emprunt.",
                  ["Avantages fonds ?", "Avantages emprunt ?", "Impact gouvernance.", "Impact BFR et covenants.", "D\u00e9cision argument\u00e9e."],
                  "Emprunt pr\u00e9serve contr\u00f4le mais charge annuit\u00e9s.\nFonds apporte r\u00e9seau mais dilution 30 %.\nD\u00e9cision selon profil risque.",
                  "Arbitrage financement justifi\u00e9."),
    ),
    # ch4
    dict(
        ch=4, company="LogiTrans", sector="transport routier", city="Le Havre", ca="28 M\u20ac", staff=210,
        themes=[
            ("e1", "GPEC : d\u00e9finition et enjeux", "GPEC",
             "LogiTrans lance une GPEC pour anticiper p\u00e9nurie chauffeurs (-12 % candidats/an) et mont\u00e9e en comp\u00e9tences logistique digitale.",
             "GPEC, anticipation besoins comp\u00e9tences"),
            ("e2", "Pr\u00e9vision RH quantitative", "pr\u00e9vision quantitative des effectifs",
             "Effectifs 210, turnover 14 %, croissance +8 % CA \u2192 besoin net +18 conducteurs et 6 dispatchers d'ici 2026.",
             "effectifs, turnover, sc\u00e9narios quantitatifs"),
            ("e3", "Pr\u00e9vision RH qualitative", "pr\u00e9vision qualitative des comp\u00e9tences",
             "Besoin FCO, ADR, comp\u00e9tences TMS (Transport Management System) et \u00e9co-conduite pour 70 % de la flotte.",
             "comp\u00e9tences futures, cartographie"),
            ("e4", "Recrutement interne et externe", "recrutement",
             "40 % postes pourvus en interne (promotion conducteurs\u2192formateurs), 60 % externe (P\u00f4le Emploi, Indeed, cooptation).",
             "canaux recrutement, co\u00fbts, d\u00e9lais"),
            ("e5", "Formation et mont\u00e9e en comp\u00e9tences", "formation professionnelle",
             "Plan formation 420 000 \u20ac/an : FCO, TMS, s\u00e9curit\u00e9. 85 % salari\u00e9s form\u00e9s, ROI estim\u00e9 baisse sinistres -18 %.",
             "plan de formation, ROI, adaptation"),
            ("e6", "Mobilit\u00e9 interne et GPEC", "mobilit\u00e9 interne",
             "Parcours conducteur \u2192 r\u00e9gulateur \u2192 responsable exploitation sur 5 ans.",
             "mobilit\u00e9, fid\u00e9lisation, GPEC"),
            ("e7", "Marque employeur et attractivit\u00e9", "marque employeur",
             "Campagne \u00ab LogiTrans s'engage \u00bb : salaires +3 %, quarts am\u00e9nag\u00e9s, 15 % femmes conductrices objectif 2027.",
             "attractivit\u00e9, diversit\u00e9, r\u00e9tention"),
            ("e8", "Gestion des d\u00e9parts et succession", "gestion des d\u00e9parts",
             "12 d\u00e9parts retraite 2025-2026, plan succession chefs d'agence.",
             "d\u00e9parts, succession, transmission savoir"),
            ("e9", "Indicateurs RH de pilotage", "indicateurs RH",
             "Turnover 14 %, absent\u00e9isme 6,2 %, co\u00fbt recrutement 4 800 \u20ac/poste, taux couverture formation 92 %.",
             "KPI RH, tableaux de bord"),
            ("e10", "Synth\u00e8se GPEC LogiTrans", "synth\u00e8se GPEC",
             "Automatisation dispatch : -8 postes administratifs, +comp\u00e9tences data. GPEC r\u00e9vis\u00e9e.",
             "GPEC et transformation num\u00e9rique RH"),
        ],
        cas1=item("cas1", "\u00c9tude de cas : P\u00e9nurie de chauffeurs",
                  "Turnover 18 % sur conducteurs, 22 postes vacants, clients m\u00e9contents d\u00e9lais. Budget RH 1,2 M\u20ac.",
                  "Plan GPEC complet sur 3 ans.",
                  ["Diagnostic quanti/quali.", "Plan recrutement.", "Plan formation.", "Marque employeur.", "Indicateurs de suivi."],
                  "GPEC 3 ans : recrutement cooptation, formation TMS, marque employeur, KPI turnover.",
                  "Plan GPEC structur\u00e9."),
        cas2=item("cas2", "\u00c9tude de cas : Automatisation et reconversion",
                  "TMS automatise planification : 8 ETP menac\u00e9s, besoin 4 data analysts. CSE consult\u00e9.",
                  "GPEC face \u00e0 l'automatisation.",
                  ["Impact quantitatif.", "Impact qualitatif.", "Plan reconversion.", "Dialogue social.", "Recommandation DRH."],
                  "Reconversion interne prioritaire, formation data, externalisation limit\u00e9e.\nAccord CSE sur plan emploi.",
                  "GPEC transformation justifi\u00e9e."),
    ),
    # ch5
    dict(
        ch=5, company="M\u00e9talPro", sector="m\u00e9tallurgie", city="Saint-\u00c9tienne", ca="18 M\u20ac", staff=140,
        themes=[
            ("e1", "Innovation de proc\u00e9d\u00e9s", "innovation de proc\u00e9d\u00e9",
             "M\u00e9talPro adopte soudure laser robotis\u00e9e : cadence +35 %, rebuts -40 %.",
             "proc\u00e9d\u00e9, productivit\u00e9, qualit\u00e9"),
            ("e2", "Flexibilit\u00e9 de production", "flexibilit\u00e9",
             "Lignes modulables : s\u00e9ries 50 \u00e0 5 000 pi\u00e8ces, changement outil 45 min vs 3 h avant.",
             "flexibilit\u00e9 volume et produit"),
            ("e3", "Qualit\u00e9 et certification ISO 9001", "management de la qualit\u00e9",
             "ISO 9001 renouvel\u00e9e, taux non-conformit\u00e9 0,8 %, audits clients trimestriels.",
             "qualit\u00e9, normes, am\u00e9lioration continue"),
            ("e4", "Modes de production : artisanal vs s\u00e9rie", "modes de production",
             "Atelier prototype (artisanal) vs ligne s\u00e9rie pour automotive.",
             "artisanal, s\u00e9rie, unitaire"),
            ("e5", "Production en flux tendu", "flux tendu",
             "Stocks composants r\u00e9duits de 28 \u00e0 9 jours, livraisons fournisseurs 2\u00d7/sem.",
             "flux tendu, stocks, synchronisation"),
            ("e6", "Lean et \u00e9limination des gaspillages", "lean management",
             "5S d\u00e9ploy\u00e9, kaizen 120 id\u00e9es/an, gain productivit\u00e9 8 %.",
             "muda, 5S, kaizen"),
            ("e7", "Qualit\u00e9 totale et implication", "TQM",
             "Circles qualit\u00e9, chaque op\u00e9rateur arr\u00eat ligne si d\u00e9faut d\u00e9tect\u00e9.",
             "TQM, empowerment, arr\u00eat ligne"),
            ("e8", "Flexibilit\u00e9 et sous-traitance", "sous-traitance",
             "Pic charge +40 % : sous-traitance 15 % vs heures sup internes.",
             "flexibilit\u00e9 externe vs interne"),
            ("e9", "Indicateurs production", "indicateurs de production",
             "TRS 78 %, OEE 82 %, taux service client 96 %.",
             "TRS, OEE, taux de service"),
            ("e10", "Synth\u00e8se organisation production", "synth\u00e8se production",
             "Nouveau contrat automotive exige flexibilit\u00e9 + qualit\u00e9 ppm <100.",
             "arbitrage investissements proc\u00e9d\u00e9/qualit\u00e9"),
        ],
        cas1=item("cas1", "\u00c9tude de cas : Certification IATF 16949",
                  "Client automotive exige IATF. Investissement 600 000 \u20ac, d\u00e9lai 18 mois.",
                  "Plan qualit\u00e9 et flexibilit\u00e9.",
                  ["Gap analysis qualit\u00e9.", "Investissements proc\u00e9d\u00e9.", "Formation.", "Planning.", "ROI attendu."],
                  "Plan 18 mois ISO+IATF, lean, formation op\u00e9rateurs, TRS cible 85 %.",
                  "Plan qualit\u00e9 complet."),
        cas2=item("cas2", "\u00c9tude de cas : Panne ligne et flux tendu",
                  "Rupture approvisionnement acier, stock 2 jours seulement, 3 clients en retard.",
                  "Limites du flux tendu.",
                  ["Causes.", "Cons\u00e9quences clients.", "Solutions court terme.", "Ajustement flux tendu.", "Le\u00e7ons."],
                  "S\u00e9curit\u00e9 stock minimal, second source, contrat cadre.\nFlux tendu = vigilance approvisionnement.",
                  "Analyse flux tendu approfondie."),
    ),
    # ch6
    dict(
        ch=6, company="Caf\u00e9Rouge", sector="restauration", city="Bordeaux", ca="2,4 M\u20ac", staff=38,
        themes=[
            ("e1", "Co\u00fbts fixes et co\u00fbts variables", "co\u00fbts fixes et variables",
             "Loyer 8 500 \u20ac/mois (fixe), masse variable 32 % CA, mati\u00e8res 28 % CA.",
             "classification co\u00fbts, structure"),
            ("e2", "Seuil de rentabilit\u00e9 (SR)", "seuil de rentabilit\u00e9",
             "SR = CF / taux marge sur co\u00fbts variables. CF 180 000 \u20ac/an, taux marge 42 % \u2192 SR \u2248 428 571 \u20ac CA.",
             "formule SR, interpr\u00e9tation"),
            ("e3", "Marge sur co\u00fbts variables", "marge sur co\u00fbts variables",
             "Ticket moyen 22 \u20ac, co\u00fbt variable unitaire 12,80 \u20ac \u2192 marge unitaire 9,20 \u20ac.",
             "marge unitaire, taux marge"),
            ("e4", "Point mort en couverts", "point mort",
             "SR en couverts : 428 571 / 22 \u2248 19 480 couverts/an, soit 53 couverts/jour.",
             "SR en unit\u00e9s physiques"),
            ("e5", "Effet de levier op\u00e9rationnel", "effet de levier",
             "CA +10 % au-dessus SR \u2192 r\u00e9sultat +25 % gr\u00e2ce aux co\u00fbts fixes.",
             "levier op\u00e9rationnel, marge"),
            ("e6", "Contr\u00f4le des co\u00fbts alimentaires", "contr\u00f4le des co\u00fbts",
             "Ratio mati\u00e8res cible 28 %, alerte si >30 %. Inventaires hebdomadaires.",
             "contr\u00f4le mati\u00e8res, \u00e9carts"),
            ("e7", "Analyse des \u00e9carts", "\u00e9carts sur co\u00fbts",
             "\u00c9cart d\u00e9favorable masse salariale +4 200 \u20ac vs budget (heures sup).",
             "\u00e9carts pr\u00e9vision/r\u00e9alis\u00e9, actions"),
            ("e8", "SR et d\u00e9cision d'extension", "d\u00e9cision d'investissement",
             "Second restaurant : CF +95 000 \u20ac, CA pr\u00e9visionnel 1,1 M\u20ac.",
             "SR site 2, rentabilit\u00e9"),
            ("e9", "Tableau de bord des co\u00fbts", "tableau de bord",
             "Dashboard mensuel : CA, ratio mati\u00e8res, masse, SR atteint \u00e0 94 % en octobre.",
             "pilotage co\u00fbts, alertes"),
            ("e10", "Synth\u00e8se contr\u00f4le des co\u00fbts", "synth\u00e8se co\u00fbts",
             "Inflation +8 % mati\u00e8res : augmenter prix ou r\u00e9duire portions ? Impact SR.",
             "strat\u00e9gie prix vs co\u00fbts"),
        ],
        cas1=item("cas1", "\u00c9tude de cas : Rentabilit\u00e9 Caf\u00e9Rouge",
                  "CA 2,4 M\u20ac, r\u00e9sultat -12 000 \u20ac. Loyer en hausse, concurrence food trucks.",
                  "Diagnostic co\u00fbts et SR.",
                  ["Classification CF/CV.", "Calcul SR.", "Analyse \u00e9carts.", "Leviers rentabilit\u00e9.", "Plan 6 mois."],
                  "SR \u00e9lev\u00e9 par loyer bordelais.\nLeviers : ticket moyen, rotation, ratio mati\u00e8res.\nPlan action chiffr\u00e9.",
                  "Diagnostic co\u00fbts complet."),
        cas2=item("cas2", "\u00c9tude de cas : Ouverture second site",
                  "Local Chartrons : loyer 9 200 \u20ac, CA pr\u00e9vu 980 000 \u20ac, investissement 120 000 \u20ac.",
                  "D\u00e9cision d'ouverture via SR.",
                  ["SR site 2.", "D\u00e9lai retour investissement.", "Risques.", "Sc\u00e9nario pessimiste.", "Go/no-go."],
                  "SR site 2 \u00e0 calculer, marge identique 42 %.\nGo si SR < 85 % CA pr\u00e9vu et tr\u00e9sorerie ok.",
                  "D\u00e9cision chiffr\u00e9e."),
    ),
    # ch7
    dict(
        ch=7, company="Plastiform", sector="plasturgie", city="Oyonnax", ca="22 M\u20ac", staff=165,
        themes=[
            ("e1", "SI de production (ERP/MES)", "syst\u00e8me d'information de production",
             "ERP SAP + MES shopfloor : tra\u00e7abilit\u00e9 lots, temps cycle temps r\u00e9el.",
             "ERP, MES, int\u00e9gration"),
            ("e2", "Automatisation et robots", "automatisation",
             "12 robots injection, cadence +22 %, effectifs production -8 % r\u00e9affect\u00e9s maintenance.",
             "robots, productivit\u00e9, emploi"),
            ("e3", "RPA en gestion administrative", "RPA",
             "RPA factures fournisseurs : 2 400 factures/mois, erreurs -90 %, 1,5 ETP \u00e9conomis\u00e9.",
             "RPA, processus r\u00e9p\u00e9titifs"),
            ("e4", "D\u00e9mat\u00e9rialisation documentaire", "d\u00e9mat\u00e9rialisation",
             "Bons de production papier \u2192 tablettes, archivage cloud certifi\u00e9.",
             "d\u00e9mat\u00e9rialisation, gains"),
            ("e5", "Industrie 4.0 et IoT", "Industrie 4.0",
             "Capteurs temp\u00e9rature moules, maintenance pr\u00e9dictive, -15 % pannes.",
             "IoT, maintenance pr\u00e9dictive"),
            ("e6", "Cobotisation", "collaboration homme-robot",
             "Cobots emballage : ergonomie am\u00e9lior\u00e9e, TMS -25 %.",
             "cobots, s\u00e9curit\u00e9, ergonomie"),
            ("e7", "SI et s\u00e9curit\u00e9 industrielle", "cybers\u00e9curit\u00e9 industrielle",
             "Segmentation r\u00e9seau OT/IT, sauvegardes MES, plan reprise 4 h.",
             "OT/IT, cyber industriel"),
            ("e8", "Formation aux nouvelles technologies", "formation num\u00e9rique",
             "120 h/an/op\u00e9rateur robots et MES, budget 180 000 \u20ac.",
             "mont\u00e9e comp\u00e9tences num\u00e9riques"),
            ("e9", "ROI des investissements num\u00e9riques", "retour sur investissement",
             "Projet IoT 380 000 \u20ac, gains maintenance 95 000 \u20ac/an \u2192 payback 4 ans.",
             "ROI, payback, crit\u00e8res investissement"),
            ("e10", "Synth\u00e8se SI production", "synth\u00e8se SI production",
             "Feuille de route 2025-2028 : ERP, MES, IoT, RPA. Priorisation budget 1,2 M\u20ac.",
             "roadmap num\u00e9rique production"),
        ],
        cas1=item("cas1", "\u00c9tude de cas : Feuille de route Industrie 4.0",
                  "Budget 1,2 M\u20ac, 4 projets en concurrence : IoT, RPA, cobots, ERP module qualit\u00e9.",
                  "Priorise les investissements SI production.",
                  ["Crit\u00e8res choix.", "Analyse chaque projet.", "ROI compar\u00e9.", "Plan d\u00e9ploiement.", "Conduite changement."],
                  "Priorit\u00e9 IoT+cobots (s\u00e9curit\u00e9+productivit\u00e9), RPA quick win, ERP qualit\u00e9 phase 2.",
                  "Roadmap argument\u00e9e."),
        cas2=item("cas2", "\u00c9tude de cas : Cyberattaque MES",
                  "Ransomware arr\u00eate MES 36 h, 180 000 \u20ac perte CA, clients automotive alert\u00e9s.",
                  "SI production et cybers\u00e9curit\u00e9.",
                  ["Vuln\u00e9rabilit\u00e9s.", "Cons\u00e9quences.", "Plan reprise.", "Mesures pr\u00e9ventives.", "Communication clients."],
                  "Segmentation OT/IT, sauvegardes offline, PRA test\u00e9.\nCommunication transparente clients.",
                  "Analyse cyber industrielle."),
    ),
    # ch8
    dict(
        ch=8, company="Mobili\u00e8re Plus", sector="meubles", city="Laval", ca="35 M\u20ac", staff=220,
        themes=[
            ("e1", "Organisation de la production", "organisation de la production",
             "Usine Laval : decoupe, assemblage, finition, exp\u00e9dition. 4 ateliers synchronis\u00e9s.",
             "processus production, flux"),
            ("e2", "Flux tendus et kanban", "kanban",
             "Kanban composants : 120 referentiels, stock moyen 11 jours.",
             "kanban, tirage, stocks"),
            ("e3", "Lean manufacturing", "lean manufacturing",
             "VSM r\u00e9alis\u00e9e, lead time 18\u219212 jours, -33 %.",
             "VSM, lead time, lean"),
            ("e4", "Pilotage production (PCP)", "planification et contr\u00f4le production",
             "Ordonnancement hebdo, charge/capacit\u00e9 \u00e9quilibr\u00e9e 92 %.",
             "PCP, ordonnancement, capacit\u00e9"),
            ("e5", "Indicateurs de pilotage", "indicateurs de pilotage",
             "OTD 94 %, WIP r\u00e9duit 20 %, productivit\u00e9 +7 %.",
             "OTD, WIP, productivit\u00e9"),
            ("e6", "Goulots d'\u00e9tranglement", "th\u00e9orie des contraintes",
             "Atelier finition = goulot, TOC appliqu\u00e9e, buffer avant finition.",
             "goulot, TOC, buffer"),
            ("e7", "Qualit\u00e9 en flux tendu", "qualit\u00e9 en production",
             "Poka-yoke assemblage, d\u00e9fauts -45 %.",
             "poka-yoke, qualit\u00e9 source"),
            ("e8", "Flexibilit\u00e9 et cellules de production", "cellules de production",
             "Cellules U pour gamme premium, ligne flow pour standard.",
             "cellules vs lignes"),
            ("e9", "Am\u00e9lioration continue", "am\u00e9lioration continue",
             "A3 problem solving, 80 projets kaizen/an.",
             "A3, kaizen, culture"),
            ("e10", "Synth\u00e8se pilotage production", "synth\u00e8se pilotage",
             "Pic commandes +30 % Black Friday : plan capacit\u00e9 temporaire.",
             "pilotage capacit\u00e9, flexibilit\u00e9"),
        ],
        cas1=item("cas1", "\u00c9tude de cas : Retards livraison",
                  "OTD tombe \u00e0 87 %, clients enseigne d\u00e9senchant\u00e9s, p\u00e9nalit\u00e9s 120 000 \u20ac.",
                  "Diagnostic lean et pilotage.",
                  ["Cartographie flux.", "Identification goulots.", "Actions lean.", "Indicateurs cibles.", "Plan 90 jours."],
                  "Goulot finition, kanban renforc\u00e9, heures modulables, OTD cible 95 %.",
                  "Plan am\u00e9lioration OTD."),
        cas2=item("cas2", "\u00c9tude de cas : Nouvelle usine agile",
                  "Investissement usine 8 M\u20ac, concept usine 4.0 lean, effectif -5 % mais comp\u00e9tences +.",
                  "Conception organisation production.",
                  ["Principes lean retenus.", "SI pilotage.", "Formation.", "Risques sociaux.", "KPI cibles."],
                  "Usine modular, MES, cellules flexibles, mont\u00e9e comp\u00e9tences, accompagnement social.",
                  "Projet usine structur\u00e9."),
    ),
    # ch9
    dict(
        ch=9, company="CleanEco", sector="nettoyage professionnel", city="Montpellier", ca="9 M\u20ac", staff=320,
        themes=[
            ("e1", "Acteurs internes de l'organisation", "parties prenantes internes",
             "CleanEco : 320 agents, 25 encadrants, direction, CSE 11 membres, actionnaires familiaux.",
             "salari\u00e9s, managers, actionnaires, CSE"),
            ("e2", "Int\u00e9r\u00eats convergents et divergents", "int\u00e9r\u00eats des acteurs",
             "Direction veut marge +2 pts, agents veulent +4 % salaire, clients veulent prix stable.",
             "convergence/divergence, n\u00e9gociation"),
            ("e3", "Culture d'entreprise", "culture d'entreprise",
             "Valeurs : respect, fiabilit\u00e9, \u00e9cologie. Turnover 22 % malgr\u00e9 valeurs affich\u00e9es.",
             "valeurs, normes, \u00e9cart discours/pratique"),
            ("e4", "Dynamique de groupe", "dynamique de groupe",
             "\u00c9quipe 12 agents immeuble tertiaire : conflit r\u00e9partition zones, m\u00e9diation RH.",
             "coh\u00e9sion, conflits, r\u00f4les"),
            ("e5", "RSE et parties prenantes", "RSE",
             "Produits \u00e9colabel, contrats insertion 8 % effectifs, charte fournisseurs.",
             "RSE, parties prenantes, performance sociale"),
            ("e6", "Dialogue social", "dialogue social",
             "N\u00e9gociation annuelle obligatoire, accords QVT sign\u00e9s 2024.",
             "CSE, n\u00e9gociation, QVT"),
            ("e7", "Conflits et m\u00e9diation", "gestion des conflits",
             "Gr\u00e8ve 2 jours site a\u00e9roport, demande prime nuit. M\u00e9diation aboutie.",
             "conflit collectif, m\u00e9diation"),
            ("e8", "Engagement des salari\u00e9s", "engagement",
             "Enqu\u00eate engagement score 62/100, plan action reconnaissance et formation.",
             "engagement, leviers motivation"),
            ("e9", "Parties prenantes externes", "parties prenantes externes",
             "Clients, fournisseurs, collectivit\u00e9s, associations environnement.",
             "clients, fournisseurs, environnement"),
            ("e10", "Synth\u00e8se acteurs et RSE", "synth\u00e8se parties prenantes",
             "Appel d'offres exige crit\u00e8res RSE 20 % note, CleanEco doit renforcer preuves.",
             "RSE dans appels d'offres"),
        ],
        cas1=item("cas1", "\u00c9tude de cas : Gr\u00e8ve et n\u00e9gociation",
                  "Gr\u00e8ve site a\u00e9roport, 40 agents, m\u00e9dia local, client menace r\u00e9siliation.",
                  "Gestion acteurs et conflit.",
                  ["Cartographie acteurs.", "Int\u00e9r\u00eats divergents.", "Strat\u00e9gie n\u00e9gociation.", "Communication.", "Accord durable."],
                  "M\u00e9diation, prime nuit partielle, QVT, calendrier revu.\nPr\u00e9server client et CSE.",
                  "Gestion conflit structur\u00e9e."),
        cas2=item("cas2", "\u00c9tude de cas : RSE et appel d'offres",
                  "March\u00e9 h\u00f4pital 2 M\u20ac/an, crit\u00e8res RSE 25 %, concurrent greenwashing suspect\u00e9.",
                  "RSE cr\u00e9dible vs greenwashing.",
                  ["Preuves RSE CleanEco.", "Risque greenwashing concurrent.", "Argumentaire diff\u00e9renciant.", "Indicateurs.", "Recommandation commerciale."],
                  "Tra\u00e7abilit\u00e9 produits, insertion, audits.\nArgumentaire factuel vs all\u00e9gations concurrent.",
                  "Strat\u00e9gie RSE commerciale."),
    ),
    # ch10
    dict(
        ch=10, company="ServicePlus", sector="services aux entreprises", city="Paris", ca="15 M\u20ac", staff=180,
        themes=[
            ("e1", "Styles de direction Likert", "styles de direction Likert",
             "ServicePlus : style consultatif en bureau d'\u00e9tudes, exploitatif en astreinte 24/7.",
             "exploitatif, benevolent, participatif, consultatif"),
            ("e2", "Motivation intrins\u00e8que et extrins\u00e8que", "motivation",
             "Enqu\u00eate : 58 % motiv\u00e9s par reconnaissance, 42 % par r\u00e9mun\u00e9ration variable.",
             "Herzberg, leviers motivation"),
            ("e3", "R\u00e9mun\u00e9ration et variables", "r\u00e9mun\u00e9ration",
             "Fixe + variable 15 % CA individuel pour commerciaux, prime collective QVT 800 \u20ac max.",
             "fixe/variable, equity"),
            ("e4", "Mobilisation des RH", "mobilisation des ressources humaines",
             "Programme ambassadeurs clients : 24 volontaires, satisfaction +12 pts.",
             "mobilisation, engagement"),
            ("e5", "Management participatif", "management participatif",
             "Comit\u00e9s projet autonomes, budget d\u00e9l\u00e9gu\u00e9 50 000 \u20ac/projet.",
             "participation, autonomie"),
            ("e6", "Feedback et reconnaissance", "reconnaissance",
             "Entretiens annuels revus, feedback continu via app Peakon.",
             "feedback, reconnaissance"),
            ("e7", "D\u00e9l\u00e9gation et responsabilisation", "d\u00e9l\u00e9gation",
             "Managers form\u00e9s d\u00e9l\u00e9gation, N-1 pilote 3 KPI autonomes.",
             "d\u00e9l\u00e9gation, responsabilisation"),
            ("e8", "Co\u00fbt de la d\u00e9motivation", "d\u00e9motivation",
             "Turnover cadres 19 %, co\u00fbt remplacement 45 000 \u20ac/cadre.",
             "turnover, co\u00fbt d\u00e9motivation"),
            ("e9", "N\u00e9gociation salariale", "n\u00e9gociation salariale",
             "NAO 2025 : +2,8 % + participation, CSE demandait +4 %.",
             "NAO, dialogue social"),
            ("e10", "Synth\u00e8se direction et motivation", "synth\u00e8se management",
             "Fusion deux entit\u00e9s : styles manag\u00e9riaux oppos\u00e9s, plan harmonisation.",
             "fusion, culture manag\u00e9riale"),
        ],
        cas1=item("cas1", "\u00c9tude de cas : Turnover cadres commerciaux",
                  "Turnover 24 % commerciaux, variable per\u00e7u in\u00e9quitable, clients perdus.",
                  "Plan motivation et r\u00e9mun\u00e9ration.",
                  ["Diagnostic motivation.", "Style direction adapt\u00e9.", "R\u00e9forme variable.", "Reconnaissance.", "KPI 12 mois."],
                  "Variable transparente, coaching, style consultatif, turnover cible 12 %.",
                  "Plan RH motivation."),
        cas2=item("cas2", "\u00c9tude de cas : Fusion et styles Likert",
                  "Fusion ServicePlus + NexCare, styles autocratique vs participatif, gr\u00e8ve symbolique.",
                  "Harmoniser styles de direction.",
                  ["Cartographie styles.", "R\u00e9sistances.", "Plan conduite changement.", "Formation managers.", "Indicateurs fusion."],
                  "Charte management participatif progressif, formation Likert, co-construction KPI.",
                  "Fusion manag\u00e9riale structur\u00e9e."),
    ),
    # ch11
    dict(
        ch=11, company="BanqueNord", sector="banque r\u00e9gionale", city="Lille", ca="95 M\u20ac", staff=650,
        themes=[
            ("e1", "Transformation num\u00e9rique", "transformation num\u00e9rique",
             "BanqueNord : 68 % op\u00e9rations via app mobile, fermeture 12 agences, digitalisation pr\u00eats.",
             "digitalisation, canaux, parcours client"),
            ("e2", "SI bancaire et omnicanal", "syst\u00e8me d'information",
             "Core banking migr\u00e9 cloud, CRM unifi\u00e9, parcours client omnicanal.",
             "SI, omnicanal, int\u00e9gration"),
            ("e3", "Conduite du changement", "conduite du changement",
             "Plan Kotter : coalition, vision, quick wins, ancrage culturel.",
             "Kotter, r\u00e9sistances, accompagnement"),
            ("e4", "R\u00e9sistances au changement", "r\u00e9sistance au changement",
             "Conseillers craignent obsolescence, 35 % sceptiques en enqu\u00eate interne.",
             "r\u00e9sistances, peurs, leviers"),
            ("e5", "Formation transformation digitale", "formation au changement",
             "400 h formation/conseiller digital, certification interne.",
             "mont\u00e9e comp\u00e9tences digitales"),
            ("e6", "Agilit\u00e9 organisationnelle", "agilit\u00e9",
             "Squads produit digital, m\u00e9thode Scrum, releases bimensuelles app.",
             "agile, squads, time-to-market"),
            ("e7", "Gouvernance SI", "gouvernance SI",
             "Comit\u00e9 digital CODIR+DSI+ m\u00e9tiers, priorisation backlog.",
             "gouvernance, priorisation projets SI"),
            ("e8", "Conduite changement et CSE", "dialogue social et changement",
             "CSE consult\u00e9 fermetures agences, PSE \u00e9vit\u00e9 par reconversions internes 85 %.",
             "CSE, reconversion, PSE"),
            ("e9", "Indicateurs transformation", "indicateurs transformation num\u00e9rique",
             "Taux digital 68 %, NPS app 41, co\u00fbt/agence -22 %.",
             "KPI digital, NPS, co\u00fbts"),
            ("e10", "Synth\u00e8se transformation", "synth\u00e8se transformation num\u00e9rique",
             "Prochaine vague : IA conseil client, craintes \u00e9thiques et emploi.",
             "IA, enjeux humains et SI"),
        ],
        cas1=item("cas1", "\u00c9tude de cas : Fermeture d'agences",
                  "12 fermetures, 45 postes concern\u00e9s, m\u00e9diatisation n\u00e9gative, app mobile +25 % usage.",
                  "Transformation et conduite changement.",
                  ["Vision digitale.", "Plan accompagnement.", "Communication.", "Indicateurs succ\u00e8s.", "Risques."],
                  "Reconversion conseillers vers remote support, communication locale, KPI digital et satisfaction.",
                  "Conduite changement agences."),
        cas2=item("cas2", "\u00c9tude de cas : IA et conseillers",
                  "Chatbot IA traite 40 % demandes simples, crainte suppressions postes conseillers.",
                  "SI, IA et conduite changement.",
                  ["Impacts emploi.", "Formation.", "Gouvernance \u00e9thique IA.", "Communication interne.", "Plan 24 mois."],
                  "IA = assistance pas remplacement, mont\u00e9e comp\u00e9tences conseil \u00e0 valeur ajout\u00e9e, charte \u00e9thique.",
                  "Transformation IA accompagn\u00e9e."),
    ),
    # ch12
    dict(
        ch=12, company="Mode&Co", sector="mode retail", city="Paris", ca="42 M\u20ac", staff=280,
        themes=[
            ("e1", "Communication interne", "communication interne",
             "Intranet, newsletter hebdo, r\u00e9unions boutique, taux lecture 71 %.",
             "canaux internes, coh\u00e9sion"),
            ("e2", "Communication externe", "communication externe",
             "Campagnes pub, RP, r\u00e9seaux sociaux 890 k followers, budget com 3,2 M\u20ac.",
             "mix communication externe"),
            ("e3", "Image de marque", "image de marque",
             "Positionnement mode durable accessible, rebranding 2024, notori\u00e9t\u00e9 assist\u00e9e 34 %.",
             "identit\u00e9, positionnement, notori\u00e9t\u00e9"),
            ("e4", "Strat\u00e9gie communication", "strat\u00e9gie de communication",
             "Plan com 2025 : lancement gamme recycl\u00e9e, objectif +8 pts image \u00e9co.",
             "objectifs, cibles, messages"),
            ("e5", "Crise communicationnelle", "gestion de crise",
             "Pol\u00e9mique travail enfants sous-traitant Asie, communiqu\u00e9 sous 24 h, audit annonc\u00e9.",
             "crise, r\u00e9activit\u00e9, transparence"),
            ("e6", "Communication digitale", "communication digitale",
             "TikTok + Instagram Reels, UGC clients, influenceurs micro 50-200 k.",
             "digital, UGC, influence"),
            ("e7", "Communication RSE", "communication RSE",
             "Campagne transparence supply chain, QR code tra\u00e7abilit\u00e9 produits.",
             "RSE, transparence, preuves"),
            ("e8", "Identit\u00e9 visuelle et coh\u00e9rence", "identit\u00e9 visuelle",
             "Charte graphique 2024, d\u00e9clinaison 1200 points vente partenaires.",
             "identit\u00e9 visuelle, d\u00e9clinaison"),
            ("e9", "Mesure efficacit\u00e9 communication", "mesure communication",
             "ROI campagne digitale 3,2, EMV influenceurs 1,8 M\u20ac, tracking brand lift.",
             "KPI com, ROI, EMV"),
            ("e10", "Synth\u00e8se communication", "synth\u00e8se communication",
             "Concurrence ultra-fast fashion, Mode&Co doit renforcer diff\u00e9renciation RSE.",
             "strat\u00e9gie int\u00e9gr\u00e9e interne/externe"),
        ],
        cas1=item("cas1", "\u00c9tude de cas : Crise sous-traitance",
                  "Documentaire TV accuse sous-traitant, hashtag boycott trending, CA online -18 % en 48 h.",
                  "Gestion crise communication.",
                  ["Chronologie crise.", "Messages cl\u00e9s.", "Canaux.", "Actions RSE.", "\u00c9valuation post-crise."],
                  "Transparence, audit ind\u00e9pendant, plan supply chain, communication empathique, preuves.",
                  "Crise com ma\u00eetris\u00e9e."),
        cas2=item("cas2", "\u00c9tude de cas : Rebranding durable",
                  "Rebranding \u00ab Mode&Co Responsible \u00bb, budget 2 M\u20ac, risque greenwashing si preuves faibles.",
                  "Strat\u00e9gie communication et image.",
                  ["Diagnostic image.", "Strat\u00e9gie cible.", "Plan m\u00e9dia.", "Preuves RSE.", "KPI 12 mois."],
                  "Campagne preuves + QR tra\u00e7abilit\u00e9, influenceurs cr\u00e9dibles, KPI notori\u00e9t\u00e9 et ventes gamme eco.",
                  "Rebranding argument\u00e9."),
    ),
    # ch13
    dict(
        ch=13, company="GreenPack", sector="emballages", city="Strasbourg", ca="16 M\u20ac", staff=110,
        themes=[
            ("e1", "\u00c9thique des affaires", "\u00e9thique des affaires",
             "GreenPack code \u00e9thique : cadeaux clients plafonn\u00e9s 50 \u20ac, alerte \u00e9thique interne.",
             "d\u00e9ontologie, code \u00e9thique"),
            ("e2", "Greenwashing", "greenwashing",
             "Concurrent affiche \u00ab 100 % vert \u00bb sans certification, GreenPack d\u00e9nonce pratiques.",
             "greenwashing, all\u00e9gations non prouv\u00e9es"),
            ("e3", "RSE washing", "RSE washing",
             "Rapport RSE concurrent : photos stock, 2 pages sur 40 sans indicateurs.",
             "RSE washing vs reporting sinc\u00e8re"),
            ("e4", "Discrimination et diversit\u00e9", "discrimination",
             "GreenPack objectif parit\u00e9 50/50 encadrement 2027, recrutement aveugle phase 1.",
             "discrimination, parit\u00e9, recrutement"),
            ("e5", "M\u00e9c\u00e9nat et sponsoring", "m\u00e9c\u00e9nat",
             "M\u00e9c\u00e9nat association tri selectif 80 000 \u20ac/an, visibilit\u00e9 logo coh\u00e9rente.",
             "m\u00e9c\u00e9nat, coh\u00e9rence RSE"),
            ("e6", "Lanceurs d'alerte", "lanceurs d'alerte",
             "Proc\u00e9dure lanceur alerte SI, signalement sous-traitant non conforme REACH.",
             "alerte \u00e9thique, protection"),
            ("e7", "\u00c9thique supply chain", "\u00e9thique supply chain",
             "Audit social fournisseurs Asie, clause RSE contrats, exclusion si non-conformit\u00e9.",
             "supply chain \u00e9thique, audits"),
            ("e8", "Conflits d'int\u00e9r\u00eats", "conflit d'int\u00e9r\u00eats",
             "Directeur achats d\u00e9missionne, lien familial fournisseur d\u00e9couvert.",
             "conflit int\u00e9r\u00eats, gouvernance"),
            ("e9", "Compliance et formation \u00e9thique", "compliance",
             "Formation \u00e9thique annuelle 100 % cadres, e-learning 2 h.",
             "compliance, formation"),
            ("e10", "Synth\u00e8se \u00e9thique et RSE", "synth\u00e8se \u00e9thique",
             "Appel d'offres exige charte \u00e9thique fournisseurs, GreenPack avantag\u00e9e.",
             "\u00e9thique comme avantage comp\u00e9titif"),
        ],
        cas1=item("cas1", "\u00c9tude de cas : Greenwashing concurrent",
                  "Concurrent GreenWrap campagne TV \u00ab 100 % naturel \u00bb, emballages plastique 80 %.",
                  "D\u00e9nonciation \u00e9thique et communication.",
                  ["Preuves greenwashing.", "Cadre juridique DGCCRF.", "Strat\u00e9gie GreenPack.", "Communication.", "Risques."],
                  "Signalement autorit\u00e9s, communication factuelle certifications FSC/OK Compost, diff\u00e9renciation preuves.",
                  "R\u00e9ponse \u00e9thique structur\u00e9e."),
        cas2=item("cas2", "\u00c9tude de cas : Conflit d'int\u00e9r\u00eats achats",
                  "Directeur achats d\u00e9missionne, contrats 1,2 M\u20ac avec soci\u00e9t\u00e9 familiale, audit interne.",
                  "\u00c9thique gouvernance et achats.",
                  ["Faits.", "Principes \u00e9thiques viol\u00e9s.", "Sanctions.", "Mesures pr\u00e9ventives.", "Communication interne/externe."],
                  "Violation conflit int\u00e9r\u00eats, resiliation contrats, renforcement compliance, transparence mesur\u00e9e.",
                  "Gestion crise \u00e9thique."),
    ),
    # ch14
    dict(
        ch=14, company="TechLink", sector="ESN", city="Rennes", ca="11 M\u20ac", staff=95,
        themes=[
            ("e1", "Nouveaux rapports au travail", "nouveaux rapports au travail",
             "TechLink : 70 % t\u00e9l\u00e9travail partiel, horaires flexibles, management par r\u00e9sultats.",
             "flexibilit\u00e9, confiance, autonomie"),
            ("e2", "T\u00e9l\u00e9travail et organisation", "t\u00e9l\u00e9travail",
             "2-3 jours TT/semaine, visio daily, coworking budget 150 \u20ac/mois/salari\u00e9.",
             "organisation TT, outils, co\u00fbts"),
            ("e3", "Droit \u00e0 la d\u00e9connexion", "droit \u00e0 la d\u00e9connexion",
             "Charte d\u00e9connexion : pas de mail apr\u00e8s 19 h ni week-end sauf astreinte.",
             "d\u00e9connexion, QVT, loi"),
            ("e4", "Modes de vie et attentes", "modes de vie",
             "Enqu\u00eate : 64 % priorit\u00e9 \u00e9quilibre vie pro/perso, 28 % mobilit\u00e9 g\u00e9ographique.",
             "aspirations, segmentation RH"),
            ("e5", "Management \u00e0 distance", "management \u00e0 distance",
             "Managers form\u00e9s 3 jours, entretiens mensuels 1:1, objectifs OKR trimestriels.",
             "management distance, OKR"),
            ("e6", "Coh\u00e9sion d'\u00e9quipe hybride", "coh\u00e9sion",
             "Semaine pr\u00e9sence mensuelle \u00e9quipe, team building trimestriel.",
             "coh\u00e9sion hybride, rituels"),
            ("e7", "QVT et bien-\u00eatre", "qualit\u00e9 de vie au travail",
             "Programme sport/sant\u00e9, psychologue entreprise, absent\u00e9isme 3,8 %.",
             "QVT, bien-\u00eatre, absent\u00e9isme"),
            ("e8", "In\u00e9galit\u00e9s TT et parit\u00e9", "in\u00e9galit\u00e9s t\u00e9l\u00e9travail",
             "Femmes cadres TT moins accord\u00e9 que hommes selon audit interne, plan correction.",
             "parit\u00e9, TT, discrimination"),
            ("e9", "Attractivit\u00e9 et marque employeur", "marque employeur",
             "Glassdoor 4,1/5, label Great Place to Work en candidature.",
             "marque employeur, TT comme atout"),
            ("e10", "Synth\u00e8se nouveaux rapports", "synth\u00e8se organisation travail",
             "Retour bureau impos\u00e9 3 jours/semaine par direction vs attentes TT 2 jours.",
             "arbitrage pr\u00e9sentiel/TT"),
        ],
        cas1=item("cas1", "\u00c9tude de cas : D\u00e9parts apr\u00e8s retour bureau",
                  "15 d\u00e9missions en 4 mois apr\u00e8s politique 3 jours pr\u00e9sentiel obligatoire.",
                  "Nouveaux rapports et r\u00e9tention.",
                  ["Diagnostic.", "Attentes salari\u00e9s.", "Benchmark.", "Nouvelle politique TT.", "Plan r\u00e9tention."],
                  "Enqu\u00eate, flexibilit\u00e9 n\u00e9goci\u00e9e, charte d\u00e9connexion renforc\u00e9e, marque employeur TT.",
                  "Politique TT r\u00e9vis\u00e9e."),
        cas2=item("cas2", "\u00c9tude de cas : Droit d\u00e9connexion en crise",
                  "Projet client urgent, mails 23 h, burnout 2 consultants, m\u00e9dia LinkedIn viral.",
                  "D\u00e9connexion et crise projet.",
                  ["Violations charte.", "Responsabilit\u00e9s.", "Actions imm\u00e9diates.", "R\u00e8gles projet.", "Communication."],
                  "Stop mails nocturnes, astreinte formalis\u00e9e, manager form\u00e9, soutien burnout, charte rappel\u00e9e.",
                  "Crise QVT g\u00e9r\u00e9e."),
    ),
    # ch15
    dict(
        ch=15, company="DataSecure", sector="cybers\u00e9curit\u00e9", city="Sophia Antipolis", ca="8 M\u20ac", staff=62,
        themes=[
            ("e1", "RGPD et donn\u00e9es personnelles", "RGPD",
             "DataSecure traite donn\u00e9es clients PME : registre traitements, DPO d\u00e9sign\u00e9, bases l\u00e9gales document\u00e9es.",
             "RGPD, bases l\u00e9gales, registre"),
            ("e2", "R\u00f4le de la CNIL", "CNIL",
             "Contr\u00f4le CNIL 2024 : recommandations dur\u00e9e conservation et droits acc\u00e8s, mise en conformit\u00e9 90 jours.",
             "CNIL, contr\u00f4le, sanctions"),
            ("e3", "Droits des personnes", "droits des personnes",
             "Proc\u00e9dure droit acc\u00e8s/effacement sous 30 jours, portail self-service.",
             "acc\u00e8s, rectification, effacement, portabilit\u00e9"),
            ("e4", "S\u00e9curit\u00e9 des donn\u00e9es", "cybers\u00e9curit\u00e9",
             "Chiffrement AES-256, MFA obligatoire, pentests annuels, SOC 24/7.",
             "s\u00e9curit\u00e9, chiffrement, MFA"),
            ("e5", "Violation de donn\u00e9es", "violation de donn\u00e9es",
             "Incident 2023 : 1 200 emails expos\u00e9s 6 h, notification CNIL 72 h, clients inform\u00e9s.",
             "breach, notification, PRA"),
            ("e6", "Blockchain et tra\u00e7abilit\u00e9", "blockchain",
             "POC blockchain logs acc\u00e8s donn\u00e9es, immutabilit\u00e9 audit trail.",
             "blockchain, tra\u00e7abilit\u00e9, limites"),
            ("e7", "Privacy by design", "privacy by design",
             "Nouveau produit SaaS : anonymisation par d\u00e9faut, param\u00e8tres vie priv\u00e9e granulaires.",
             "privacy by design, minimisation"),
            ("e8", "Sous-traitants et responsabilit\u00e9", "sous-traitance RGPD",
             "Clauses RGPD contrats AWS et h\u00e9bergeur, audit sous-traitants triennal.",
             "sous-traitant, responsabilit\u00e9 conjointe"),
            ("e9", "Formation sensibilisation", "sensibilisation RGPD",
             "Phishing simul\u00e9 mensuel, taux clic 4 % vs 18 % avant formation.",
             "sensibilisation, phishing, culture s\u00e9curit\u00e9"),
            ("e10", "Synth\u00e8se responsabilit\u00e9 num\u00e9rique", "synth\u00e8se responsabilit\u00e9 num\u00e9rique",
             "Offre IA analyse logs : risque profilage, DPIA requise.",
             "DPIA, IA, conformit\u00e9"),
        ],
        cas1=item("cas1", "\u00c9tude de cas : Contr\u00f4le CNIL",
                  "CNIL contr\u00f4le DataSecure : conservation excessive, DPIA manquante module IA, d\u00e9lai 90 jours.",
                  "Plan mise en conformit\u00e9 RGPD.",
                  ["\u00c9carts identifi\u00e9s.", "Plan actions.", "Gouvernance DPO.", "Communication clients.", "Pr\u00e9vention r\u00e9cidive."],
                  "Dur\u00e9es conservation revues, DPIA IA, registre \u00e0 jour, proc\u00e9dures droits renforc\u00e9es.",
                  "Conformit\u00e9 RGPD structur\u00e9e."),
        cas2=item("cas2", "\u00c9tude de cas : Ransomware et donn\u00e9es clients",
                  "Ransomware chiffre serveurs, fuite possible 50 000 dossiers clients PME, ran\u00e7on 200 BTC.",
                  "Cybers\u00e9curit\u00e9 et RGPD en crise.",
                  ["Chronologie.", "Obligations CNIL/clients.", "Ne pas payer ran\u00e7on ?", "PRA.", "Le\u00e7ons conformit\u00e9."],
                  "Notification 72 h, pas de ran\u00e7on, restauration backup, renforcement MFA/SOC, communication transparente.",
                  "Crise cyber-RGPD ma\u00eetris\u00e9e."),
    ),
]


def main():
    for spec in CHAPTER_DEFS:
        ch = spec["ch"]
        items = build_chapter(
            ch, spec["company"], spec["sector"], spec["city"],
            spec["ca"], spec["staff"], spec["themes"], spec["cas1"], spec["cas2"],
        )
        write_chapter(ch, items)
    print(f"done: {len(CHAPTER_DEFS)} chapters -> {OUT}")


if __name__ == "__main__":
    main()
