# -*- coding: utf-8 -*-
"""
Organisations REELLES pour les exercices Management (1 exo = 1 acteur distinct).

Evite les noms fictifs type BioFresh, Locavore, Artisana...
Ne pas utiliser Locavore (risque de confusion avec des notions du cours).
"""

# Noms fictifs reels dans les modules enrich (chap11-15)
CHAPTER_FICTION: dict[int, tuple[str, ...]] = {
    3: ("Lumina", "Lumina LED", "Lumina \u00c9clairage"),
    4: ("LogiTrans",),
    5: ("M\u00e9talPro", "MetalPro"),
    6: ("Caf\u00e9Rouge", "CafeRouge"),
    7: ("Plastiform",),
    8: ("Mobili\u00e8re Plus", "Mobil\u00e8re Plus"),
    9: ("CleanEco",),
    10: ("ServicePlus",),
    11: ("BanqueNord",),
    12: ("Mode&Co", "NovaRetail"),
    13: ("GreenPack",),
    14: ("TechLink", "Horizon RH"),
    15: ("DataSecure",),
}

# Nom fil rouge fictif dans les scripts rewrite_*_data (a remplacer)
PRIMARY_FICTION: dict[int, str] = {
    1: "BioFresh",
    2: "Artisana",
    3: "Lumina LED",
    4: "LogiTrans",
    5: "M\u00e9talPro",
    6: "Caf\u00e9Rouge",
    7: "Plastiform",
    8: "Mobili\u00e8re Plus",
    9: "CleanEco",
    10: "ServicePlus",
    11: "BanqueNord",
    12: "NovaRetail",
    13: "GreenPack",
    14: "Horizon RH",
    15: "DataSecure",
}

# Autres noms fictifs a remplacer si present dans un exercice
EXTRA_FICTION = (
    "GreenBox",
    "MonPanierBio",
    "Locavore",
    "GMS Frais du Sud",
    "Asso Panier Solidaire Lyon",
    "Coop Bio Rh\u00f4ne",
    "March\u00e9 Paysan M\u00e9tropole",
    "Start-up VegoTrack",
    "R\u00e9seau Restos Bio",
    "GreenWrap",
)

# 12 acteurs reels distincts par chapitre (TPE / ETI / GE / asso / public)
REAL_ORGS_BY_CHAPTER: dict[int, list[str]] = {
    1: [
        "Picard",
        "Fnac Darty",
        "Lidl",
        "Innocent (Danone)",
        "Uber Eats",
        "Renault",
        "La Poste",
        "Vinted",
        "Action",
        "Decathlon",
        "Carrefour",
        "Danone",
    ],
    2: [
        "Etsy",
        "Vinted",
        "Amazon",
        "Blablacar",
        "Airbnb",
        "Booking.com",
        "SNCF Connect",
        "Uber",
        "Doctolib",
        "Stripe",
        "Accor",
        "Michelin",
    ],
    3: [
        "Schneider Electric",
        "Saint-Gobain",
        "Michelin",
        "LVMH",
        "Renault",
        "Safran",
        "Airbus",
        "TotalEnergies",
        "BNP Paribas",
        "Cr\u00e9dit Agricole",
        "La Banque Postale",
        "ADEME",
    ],
    4: [
        "Geodis",
        "La Poste",
        "SNCF",
        "Air France",
        "Carrefour",
        "Amazon France",
        "Chronopost",
        "DHL",
        "RATP",
        "P\u00f4le emploi",
        "Mairie de Lille",
        "R\u00e9gion Hauts-de-France",
    ],
    5: [
        "Renault",
        "Safran",
        "ArcelorMittal",
        "Michelin",
        "L'Or\u00e9al",
        "Danone",
        "Nestl\u00e9 France",
        "Schneider Electric",
        "Dassault Aviation",
        "Stellantis",
        "INPI",
        "BPI France",
    ],
    6: [
        "Paul (Groupe Holder)",
        "McDonald's France",
        "Accor",
        "Elior",
        "Restos du C\u0153ur",
        "Mairie de Bordeaux",
        "Sodexo",
        "Deliveroo",
        "Mercure",
        "CCI Nouvelle-Aquitaine",
        "Les Halles de Bacalan",
        "UCPA",
    ],
    7: [
        "Veolia",
        "Suez",
        "Danone",
        "Tetra Pak",
        "Nestl\u00e9",
        "Les Canaux",
        "Syndicat mixte des d\u00e9chets",
        "Emma\u00fcs",
        "Decathlon",
        "Loop (TerraCycle)",
        "ADEME",
        "M\u00e9tropole de Lyon",
    ],
    8: [
        "IKEA France",
        "But",
        "Conforama",
        "Leroy Merlin",
        "Habitat",
        "Emma\u00fcs",
        "Office HLM",
        "Les Compagnons du devoir",
        "Renault",
        "Anah",
        "Minist\u00e8re du Logement",
        "Banque des territoires",
    ],
    9: [
        "Veolia Propret\u00e9",
        "Onet",
        "Suez",
        "Accor",
        "Secours populaire",
        "Mairie de Nantes",
        "Coop\u00e9rative Scop",
        "Orange",
        "Doctolib",
        "CHU de Toulouse",
        "CSE d'Airbus",
        "Fondation de France",
    ],
    10: [
        "Capgemini",
        "Randstad",
        "Accenture",
        "Manpower",
        "Secours catholique",
        "Maison de l'emploi",
        "Scop",
        "Orange",
        "LinkedIn",
        "P\u00f4le emploi",
        "Inspection du travail",
        "URSSAF",
    ],
    11: [
        "Cr\u00e9dit Agricole",
        "BNP Paribas",
        "La Banque Postale",
        "Revolut",
        "Association pour l'emploi des cadres",
        "Tr\u00e9sorerie de Paris",
        "Nef (Nouvelle \u00e9conomie fraternelle)",
        "PayPal",
        "Stripe",
        "DGFiP",
        "AMF",
        "Banque de France",
    ],
    12: [
        "Kiabi",
        "Decathlon",
        "H&M",
        "Zara",
        "Uniqlo",
        "Celio",
        "Etam",
        "Lacoste",
        "Nike",
        "Petit Bateau",
        "Monoprix",
        "Galeries Lafayette",
    ],
    13: [
        "GreenPack",
        "Nestl\u00e9",
        "Patagonia",
        "Greenpeace",
        "Emma\u00fcs",
        "DGCCRF",
        "Biocoop",
        "L'Or\u00e9al",
        "Too Good To Go",
        "Amnesty International",
        "Comit\u00e9 d'\u00e9thique Danone",
        "CSE de L'Or\u00e9al",
    ],
    14: [
        "Capgemini",
        "Accenture",
        "Atos",
        "Sopra Steria",
        "Orange",
        "SNCF",
        "Blablacar",
        "Doctolib",
        "Vinted",
        "ADEME",
        "France Travail",
        "Mairie de Grenoble",
    ],
    15: [
        "Orange Cyberdefense",
        "Microsoft France",
        "Google France",
        "Doctolib",
        "La Quadrature du Net",
        "CNIL",
        "Wikimedia France",
        "Amazon Web Services",
        "ANSSI",
        "Comit\u00e9 d'\u00e9thique Orange",
        "Universit\u00e9 Paris-Saclay",
        "Commission europ\u00e9enne (RGPD)",
    ],
}

# ch13 still had GreenPack in list - replace with real company
REAL_ORGS_BY_CHAPTER[13] = [
    "L'Or\u00e9al",
    "Nestl\u00e9",
    "Patagonia",
    "Greenpeace",
    "Emma\u00fcs",
    "DGCCRF",
    "Biocoop",
    "Danone",
    "Too Good To Go",
    "Amnesty International",
    "Comit\u00e9 d'\u00e9thique Danone",
    "CSE de L'Or\u00e9al",
]
