# -*- coding: utf-8 -*-
"""12 organisations distinctes par chapitre Management (1 exo = 1 orga)."""

# orga dominante actuelle dans les supports (fil rouge a remplacer par exercice)
PRIMARY_ORG: dict[int, str] = {
    1: "BioFresh",
    2: "Artisana",
    3: "Lumina",
    4: "LogiTrans",
    5: "M\u00e9talPro",
    6: "Caf\u00e9Rouge",
    7: "Plastiform",
    8: "Mobil\u00e8re Plus",
    9: "CleanEco",
    10: "ServicePlus",
    11: "BanqueNord",
    12: "NovaRetail",
    13: "GreenPack",
    14: "Horizon RH",
    15: "DataSecure",
}

# 12 noms uniques par chapitre (PME, GE, asso, public, coop...)
ORGS_BY_CHAPTER: dict[int, list[str]] = {
    1: [
        "BioFresh",
        "GreenBox",
        "MonPanierBio",
        "Locavore",
        "Asso Panier Solidaire Lyon",
        "Coop Bio Rh\u00f4ne",
        "March\u00e9 Paysan M\u00e9tropole",
        "GMS Frais du Sud",
        "Start-up VegoTrack",
        "R\u00e9seau Restos Bio",
        "CCI Rh\u00f4ne-Alpes",
        "Office tourisme Lyon",
    ],
    2: [
        "Artisana",
        "Atelier Terre & Feu",
        "Coop C\u00e9ramistes du Sud",
        "Galeries Lafayette Maison",
        "Etsy France",
        "Asso Artisans du Monde",
        "Maison du tourisme Dordogne",
        "PME Bois & Lin",
        "Start-up CraftLink",
        "Chambre des m\u00e9tiers Occitanie",
        "Mus\u00e9e des Arts d\u00e9co",
        "Fondation Patrimoine vivant",
    ],
    3: [
        "Lumina LED",
        "Philips Lighting",
        "PME \u00c9clairage Vert",
        "Eiffage \u00c9nergie",
        "Asso Lumi\u00e8re pour tous",
        "Mairie de Grenoble",
        "Coop \u00c9nergie citoyenne",
        "Schneider Electric",
        "Start-up SmartLight",
        "H\u00f4pital universitaire",
        "R\u00e9seau Entreprises engag\u00e9es",
        "ADEME",
    ],
    4: [
        "LogiTrans",
        "Geodis",
        "PME Transports Dupont",
        "La Poste Logistique",
        "Asso Insertion Logistique",
        "M\u00e9tropole de Lille",
        "Coop Livraison \u00e9quitable",
        "Amazon Logistics",
        "Start-up FleetOpt",
        "CHU de Rennes",
        "P\u00f4le emploi Bretagne",
        "R\u00e9gion Grand Est",
    ],
    5: [
        "M\u00e9talPro",
        "ArcelorMittal",
        "PME M\u00e9canique Martin",
        "Safran",
        "Asso Reconversion Industrie",
        "Communaut\u00e9 d'agglom\u00e9ration",
        "Coop Industrie du futur",
        "Renault Group",
        "Start-up RoboFab",
        "ONERA",
        "BPI France",
        "Universit\u00e9 technologique",
    ],
    6: [
        "Caf\u00e9Rouge",
        "Boulangerie Amandine",
        "Brasserie du Port",
        "Traiteur \u00c9v\u00e9nements Plus",
        "Asso Repas solidaires",
        "Cantine scolaire Bordeaux M\u00e9tropole",
        "Coop Restauration bio",
        "Sodexo",
        "Start-up MealBox",
        "H\u00f4tel Mercure",
        "CCI Nouvelle-Aquitaine",
        "March\u00e9 couvert des Capucins",
    ],
    7: [
        "Plastiform",
        "Veolia",
        "PME Emballages Durand",
        "Danone",
        "Asso Zero D\u00e9chet",
        "Syndicat mixte d\u00e9chets",
        "Coop Recyclage citoyen",
        "Tetra Pak",
        "Start-up LoopPack",
        "Agence de l'eau",
        "ADEME",
        "Communaut\u00e9 urbaine",
    ],
    8: [
        "Mobil\u00e8re Plus",
        "IKEA France",
        "PME Menuiserie Bois",
        "But",
        "Asso Logement solidaire",
        "Office HLM r\u00e9gional",
        "Coop Habitat participatif",
        "Conforama",
        "Start-up FurniShare",
        "Anah",
        "Minist\u00e8re du Logement",
        "Banque des territoires",
    ],
    9: [
        "CleanEco",
        "Veolia Propret\u00e9",
        "PME Nettoyage Pro",
        "Onet",
        "Asso Propret\u00e9 citoyenne",
        "Mairie de Nantes",
        "Coop Services \u00e9cologiques",
        "Suez",
        "Start-up CleanTech",
        "CHU de Toulouse",
        "CSE grande entreprise",
        "Fondation entreprise",
    ],
    10: [
        "ServicePlus",
        "Capgemini",
        "PME Conseil RH Martin",
        "Randstad",
        "Asso Insertion emploi",
        "Maison de l'emploi",
        "Coop Services aux entreprises",
        "Accenture",
        "Start-up TalentHub",
        "P\u00f4le emploi",
        "Inspection du travail",
        "URSSAF",
    ],
    11: [
        "BanqueNord",
        "Cr\u00e9dit Agricole",
        "PME Conseil financier",
        "BNP Paribas",
        "Asso \u00c9ducation financi\u00e8re",
        "Tr\u00e9sorerie municipale",
        "Coop Finance solidaire",
        "Revolut",
        "Start-up PayFlow",
        "DGFiP",
        "AMF",
        "Banque de France",
    ],
    12: [
        "NovaRetail",
        "Carrefour",
        "PME \u00c9picerie du coin",
        "Decathlon",
        "Asso Consommation responsable",
        "M\u00e9diath\u00e8que municipale",
        "Coop Commerce \u00e9quitable",
        "Amazon France",
        "Start-up ShopLocal",
        "DGCCRF",
        "UFC Que Choisir",
        "Chambre de commerce",
    ],
    13: [
        "GreenPack",
        "GreenWrap",
        "PME Emballages Bio",
        "Halte au greenwashing",
        "Asso Halte aux d\u00e9chets",
        "DGCCRF",
        "Coop Emballages compostables",
        "Nestl\u00e9",
        "Start-up PackGreen",
        "Greenpeace",
        "Comit\u00e9 \u00e9thique GreenPack",
        "CSE GreenPack",
    ],
    14: [
        "Horizon RH",
        "PME Industrie Lorraine",
        "Groupe Safran",
        "Asso Parit\u00e9 pro",
        "Inspection du travail",
        "Coop RH citoyenne",
        "Randstad",
        "Start-up SkillMatch",
        "CSE grande entreprise",
        "D\u00e9fenseur des droits",
        "Minist\u00e8re du Travail",
        "Syndicat CGT",
    ],
    15: [
        "DataSecure",
        "Orange Cyberdefense",
        "PME Informatique Dupuis",
        "Microsoft France",
        "Asso La Quadrature",
        "CNIL",
        "Coop Num\u00e9rique \u00e9thique",
        "Google France",
        "Start-up PrivaTech",
        "ANSSI",
        "Comit\u00e9 \u00e9thique entreprise",
        "Universit\u00e9 num\u00e9rique",
    ],
}
